# Add location settings on new locations.
some_loc_query = {'account' : '60b8ca26590e77d608d7c0ff',"_id":"60b8cbd010e9194b7af618c6"}
locs = pcli.locations.list_all(q=some_loc_query)

for loc in locs: 
    pcli.locations.update(loc,{
            "posSettings": {
                "simphony": {
                "sendCheckId": False,
                "sendOrderType": False,
                "rushOrder": False,
                "vipOrder": False,
                "checkEmplOrder": False,
                "allowPartialOrder": False,
                "futureOrder": False,
                "hasAuth": False,
                "revenueCenter": "1",
                "employeeObjectNumber": "10",
                "itemSubLevel": 3,
                "itemMenuLevel": 1,
                "posVersion": "18.2",
                "paidPaymentType": "101",
                "discountId": "104",
                "orderTypeId": "1",
                "notPaidPaymentType": "902",
                "tax1": 5,
                "taxObjectNumber1": 4,
                "priceLevel": 2,
                "timeZone": "Europe/London",
                "bufferOrders": False,
                "logOps": True,
                "anonymizeCustomer": False,
                "readonly": False,
                "useCommaAsDecimalCharacter": False,
                "cropCustomerName": False,
                "noteTemplate": "",
                "sendAddressInNoteItem": False,
                "noteItemPlu": "",
                "checkToFireDateAsap": False,
                "orderNoteTemplate": "",
                "discountPLU": "",
                "serviceChargePLU": "",
                "deliveryPLU": "",
                "modifierMultiplier": "",
                "taxExcl": False,
                "productsSyncRanges": "",
                "productsFamilyGroups": "",
                "dontLinkModGroups": False,
                "tax2": 20,
                "taxObjectNumber2": 2,
                "autoFinalizeOrders": True,
                "averagePreparationTime": 1,
                "usePLUForCharges": False,
                "pCheckInfoLinesTemplate": "",
                "dontSendPhoneNumber": False,
                "onlySendOrderDisplayIdForCheckId": False,
                "putNoteItemsAtTop": False,
                "paginateProductSync": False,
                "replaceNonAsciiSymbols": False
                }}})