import requests

url = "https://api.deliverect.com/productAndCategories"

payload = {
  "accountId" : "64067bda2c75132533973eb8",
  "locationId" : "64067e3babdbcfaaebd9bd28",
  "products" : [ {
    "productType" : 3,
    "plu" : "_ADD_GR_6",
    "name" : "Burger Additions",
    "posProductId" : "6",
    "posCategoryIds" : [ ],
    "description" : "Burger Additions",
    "subProducts" : [ "_ADD_150", "_ADD_94", "_ADD_89", "_ADD_87", "_ADD_91", "_ADD_74", "_ADD_71", "_ADD_73", "_ADD_88", "_ADD_98", "_ADD_97", "_ADD_113", "_ADD_168", "_ADD_127", "_ADD_141", "_ADD_170", "_ADD_109", "_ADD_110", "_ADD_167", "_ADD_124", "_ADD_70", "_ADD_104", "_ADD_105", "_ADD_106", "_ADD_107", "_ADD_108", "_ADD_111", "_ADD_112", "_ADD_120", "_ADD_163", "_ADD_123", "_ADD_157", "_ADD_101", "_ADD_96", "_ADD_93", "_ADD_92", "_ADD_90", "_ADD_125", "_ADD_161", "_ADD_148", "_ADD_185", "_ADD_144", "_ADD_146", "_ADD_143", "_ADD_147", "_ADD_186", "_ADD_151", "_ADD_179", "_ADD_156", "_ADD_152", "_ADD_153", "_ADD_184", "_ADD_154", "_ADD_122", "_ADD_121", "_ADD_173", "_ADD_126", "_ADD_172", "_ADD_181", "_ADD_182", "_ADD_180", "_ADD_190", "_ADD_189", "_ADD_196", "_ADD_118", "_ADD_200", "_ADD_202", "_ADD_203", "_ADD_204", "_ADD_205", "_ADD_207", "_ADD_206", "_ADD_208", "_ADD_209" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 74
  }, {
    "productType" : 2,
    "plu" : "_ADD_150",
    "price" : 0,
    "name" : "STARTER DISH",
    "posProductId" : "150",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_94",
    "price" : 0,
    "name" : "TAKEAWAY",
    "posProductId" : "94",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_89",
    "price" : 0,
    "name" : "TO SHARE",
    "posProductId" : "89",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_87",
    "price" : 350,
    "name" : "SWEET POTATO",
    "posProductId" : "87",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_91",
    "price" : 200,
    "name" : "AIOLI",
    "posProductId" : "91",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_74",
    "price" : 300,
    "name" : "BACON",
    "posProductId" : "74",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_71",
    "price" : 200,
    "name" : "CHEESE",
    "posProductId" : "71",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_73",
    "price" : 200,
    "name" : "EGG",
    "posProductId" : "73",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_88",
    "price" : 300,
    "name" : "AVOCADO",
    "posProductId" : "88",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_98",
    "price" : 350,
    "name" : "GUACAMOLE",
    "posProductId" : "98",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_97",
    "price" : 300,
    "name" : "TRUFFLE AIOLI",
    "posProductId" : "97",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_113",
    "price" : 0,
    "name" : "TAKEAWAY DRINK",
    "posProductId" : "113",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_168",
    "price" : 0,
    "name" : "SAUCES ON SIDE",
    "posProductId" : "168",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_127",
    "price" : 0,
    "name" : "SALAD NOT FRIES",
    "posProductId" : "127",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_141",
    "price" : 500,
    "name" : "GRAVY",
    "posProductId" : "141",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_170",
    "price" : 500,
    "name" : "EXTRA CHICKEN PATTIE",
    "posProductId" : "170",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_109",
    "price" : 200,
    "name" : "SWAP FOR V2 PATTIE",
    "posProductId" : "109",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_110",
    "price" : 200,
    "name" : "GARLIC DILL PICKLE",
    "posProductId" : "110",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_167",
    "price" : 200,
    "name" : "CHICKEN NOT VEGGIE",
    "posProductId" : "167",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_124",
    "price" : 200,
    "name" : "MEAT NOT VEGIE PATTIE",
    "posProductId" : "124",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_70",
    "price" : 500,
    "name" : "EXTRA BEEF PATTIE",
    "posProductId" : "70",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_104",
    "price" : 250,
    "name" : "CHICKEN NOT MEAT",
    "posProductId" : "104",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_105",
    "price" : 200,
    "name" : "GARLIC DILL PICKLE ON SIDE",
    "posProductId" : "105",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_106",
    "price" : 0,
    "name" : "CHUTNEY ON SIDE",
    "posProductId" : "106",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_107",
    "price" : 0,
    "name" : "RELISH ON SIDE",
    "posProductId" : "107",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_108",
    "price" : 0,
    "name" : "AIOLI ON SIDE",
    "posProductId" : "108",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_111",
    "price" : 200,
    "name" : "CARAMALISED ONIONS",
    "posProductId" : "111",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_112",
    "price" : 300,
    "name" : "ONION RINGS SIDE",
    "posProductId" : "112",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_120",
    "price" : 450,
    "name" : "ONION RINGS NOT FRIES",
    "posProductId" : "120",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_163",
    "price" : 200,
    "name" : "ONIONN RINGS IN BURGER",
    "posProductId" : "163",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_123",
    "price" : 200,
    "name" : "BEETROOT",
    "posProductId" : "123",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_157",
    "price" : 200,
    "name" : "DEEP FRIED JALAPENO",
    "posProductId" : "157",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_101",
    "price" : 200,
    "name" : "FRESH JALEPENO",
    "posProductId" : "101",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_96",
    "price" : 0,
    "name" : "MEDIUM",
    "posProductId" : "96",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_93",
    "price" : 0,
    "name" : "MEDIUM WELL",
    "posProductId" : "93",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_92",
    "price" : 0,
    "name" : "WELL DONE",
    "posProductId" : "92",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_90",
    "price" : 0,
    "name" : "NO BUTTER ON BUN",
    "posProductId" : "90",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_125",
    "price" : 0,
    "name" : "NO SALT ON FRIES",
    "posProductId" : "125",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_161",
    "price" : 200,
    "name" : "CAROLINA SAUCE",
    "posProductId" : "161",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_148",
    "price" : 200,
    "name" : "HOT SMOKEY SAUCE",
    "posProductId" : "148",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_185",
    "price" : 300,
    "name" : "VEGAN AIOLI",
    "posProductId" : "185",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_144",
    "price" : 200,
    "name" : "MUSTARD",
    "posProductId" : "144",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_146",
    "price" : 200,
    "name" : "TOMATO SAUCE",
    "posProductId" : "146",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_143",
    "price" : 200,
    "name" : "DIEMANS HOT SAUCE",
    "posProductId" : "143",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_147",
    "price" : 200,
    "name" : "DIEMANS MEDIUM SAUCE",
    "posProductId" : "147",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_186",
    "price" : 200,
    "name" : "BORDY AIOLI",
    "posProductId" : "186",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_151",
    "price" : 200,
    "name" : "CHUTNEY",
    "posProductId" : "151",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_179",
    "price" : 200,
    "name" : "TOMATO RELISH",
    "posProductId" : "179",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_156",
    "price" : 200,
    "name" : "HONEY AIOLI",
    "posProductId" : "156",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_152",
    "price" : 200,
    "name" : "LEMON DILL AOILI",
    "posProductId" : "152",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_153",
    "price" : 200,
    "name" : "COLESLAW",
    "posProductId" : "153",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_184",
    "price" : 100,
    "name" : "UPGRADE ONLY TO TRUFFLE",
    "posProductId" : "184",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_154",
    "price" : 200,
    "name" : "SUNDRIED TOMATO AIOLI",
    "posProductId" : "154",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_122",
    "price" : 0,
    "name" : "AIOLI NOT CHUTNEY",
    "posProductId" : "122",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_121",
    "price" : 0,
    "name" : "AIOLI NOT RELISH",
    "posProductId" : "121",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_173",
    "price" : 0,
    "name" : "EXTRA CRISPY FRIES",
    "posProductId" : "173",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_126",
    "price" : 100,
    "name" : "LETTUCE",
    "posProductId" : "126",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_172",
    "price" : 0,
    "name" : "VEGGIE NOT BEEF OR CHICKEN",
    "posProductId" : "172",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_181",
    "price" : 200,
    "name" : "PICKLED FENNEL",
    "posProductId" : "181",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_182",
    "price" : 200,
    "name" : "CUCUMBER",
    "posProductId" : "182",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_180",
    "price" : 200,
    "name" : "MUSHROOMS",
    "posProductId" : "180",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_190",
    "price" : 200,
    "name" : "BUFFALO SAUCE",
    "posProductId" : "190",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_189",
    "price" : 200,
    "name" : "BBQ SAUCE",
    "posProductId" : "189",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_196",
    "price" : 0,
    "name" : "TOMATO SAUCE IN BURGER",
    "posProductId" : "196",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_118",
    "price" : 100,
    "name" : "CHUTNEY NOT RELISH",
    "posProductId" : "118",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_200",
    "price" : 0,
    "name" : "CUT IN HALF",
    "posProductId" : "200",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_202",
    "price" : 200,
    "name" : "OLD BONES CHILLI HOT",
    "posProductId" : "202",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_203",
    "price" : 200,
    "name" : "OLD BONES CHILL MILD",
    "posProductId" : "203",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_204",
    "price" : 0,
    "name" : "SPLIT BASKETS",
    "posProductId" : "204",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_205",
    "price" : 0,
    "name" : "NORMAL FRIES",
    "posProductId" : "205",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_207",
    "price" : 0,
    "name" : "AIOLI NOT CHUTNEY ",
    "posProductId" : "207",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_206",
    "price" : 0,
    "name" : "AIOLI NOT RELISH",
    "posProductId" : "206",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_208",
    "price" : 200,
    "name" : "CHIPOTLE AIOLI",
    "posProductId" : "208",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_ADD_209",
    "price" : 350,
    "name" : "DOOR DASH SWEET POTATO",
    "posProductId" : "209",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_ADD_GR_5",
    "name" : "Beverage",
    "posProductId" : "5",
    "posCategoryIds" : [ ],
    "description" : "Beverage",
    "subProducts" : [ "_ADD_174" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_ADD_174",
    "price" : 400,
    "name" : "DOUBLE SHOT ",
    "posProductId" : "174",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_321",
    "name" : "Classic Cog Remove",
    "posProductId" : "321",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_903", "_REM_897", "_REM_898", "_REM_899", "_REM_900", "_REM_901", "_REM_902" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 7
  }, {
    "productType" : 2,
    "plu" : "_REM_903",
    "price" : 0,
    "name" : "No Aioli not chutney",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_897",
    "price" : 0,
    "name" : "No Beef",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_898",
    "price" : 0,
    "name" : "No Cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_899",
    "price" : 0,
    "name" : "No Chutney",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_900",
    "price" : 0,
    "name" : "No fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_901",
    "price" : 0,
    "name" : "No Lettuce",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_902",
    "price" : 0,
    "name" : "No Tomato Relish",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "321",
    "price" : 2195,
    "name" : "Classic Cog",
    "posProductId" : "321",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_321" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_55",
    "name" : "Trippin Zeahorse Remove",
    "posProductId" : "55",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_755", "_REM_756", "_REM_757", "_REM_758", "_REM_759", "_REM_760" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 6
  }, {
    "productType" : 2,
    "plu" : "_REM_755",
    "price" : 0,
    "name" : "No aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_756",
    "price" : 0,
    "name" : "No Bacon",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_757",
    "price" : 0,
    "name" : "No Cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_758",
    "price" : 0,
    "name" : "No fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_759",
    "price" : 0,
    "name" : "No Lettuce",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_760",
    "price" : 0,
    "name" : "No Tomato Relish",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "55",
    "price" : 2295,
    "name" : "Trippin Zeahorse",
    "posProductId" : "55",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_55" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_335",
    "name" : "#Bordy  Remove",
    "posProductId" : "335",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_589", "_REM_593", "_REM_590", "_REM_591", "_REM_592" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 5
  }, {
    "productType" : 2,
    "plu" : "_REM_589",
    "price" : 0,
    "name" : "No cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_593",
    "price" : 0,
    "name" : "No Fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_590",
    "price" : 0,
    "name" : "No pickles",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_591",
    "price" : 0,
    "name" : "No tomato aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_592",
    "price" : 0,
    "name" : "No truffle aioil",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "335",
    "price" : 2295,
    "name" : "#Bordy ",
    "posProductId" : "335",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_335" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_57",
    "name" : "Vero Valentino Remove",
    "posProductId" : "57",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_847", "_REM_848", "_REM_849", "_REM_850", "_REM_851" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 5
  }, {
    "productType" : 2,
    "plu" : "_REM_847",
    "price" : 0,
    "name" : "No aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_848",
    "price" : 0,
    "name" : "No Baby Spinach Leaves",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_849",
    "price" : 0,
    "name" : "No Cucumber",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_850",
    "price" : 0,
    "name" : "No fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_851",
    "price" : 0,
    "name" : "No Pickled Fennel",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "57",
    "price" : 2295,
    "name" : "Vero Valentino",
    "posProductId" : "57",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_57" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_56",
    "name" : "Just a Jezabel Remove",
    "posProductId" : "56",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_753", "_REM_754", "_REM_751", "_REM_752" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 4
  }, {
    "productType" : 2,
    "plu" : "_REM_753",
    "price" : 0,
    "name" : "No Aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_754",
    "price" : 0,
    "name" : "No Coleslaw",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_751",
    "price" : 0,
    "name" : "No fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_752",
    "price" : 0,
    "name" : "No Guacamole",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "56",
    "price" : 2395,
    "name" : "Just a Jezabel",
    "posProductId" : "56",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_56" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_58",
    "name" : "Johnny Collide Remove",
    "posProductId" : "58",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_861", "_REM_862", "_REM_863", "_REM_864", "_REM_865", "_REM_866", "_REM_867", "_REM_868" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 8
  }, {
    "productType" : 2,
    "plu" : "_REM_861",
    "price" : 0,
    "name" : "No cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_862",
    "price" : 0,
    "name" : "No fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_863",
    "price" : 0,
    "name" : "No honey aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_864",
    "price" : 0,
    "name" : "No mushrooms",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_865",
    "price" : 0,
    "name" : "No onion rings",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_866",
    "price" : 0,
    "name" : "No spinach leaves ",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_867",
    "price" : 0,
    "name" : "No tomato relish",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_868",
    "price" : 0,
    "name" : "No vege pattie",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "58",
    "price" : 2295,
    "name" : "Johnny Collide",
    "posProductId" : "58",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_58" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_298",
    "name" : "Delta Rigg VEGAN Remove",
    "posProductId" : "298",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_842", "_REM_843", "_REM_844", "_REM_845", "_REM_846" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 5
  }, {
    "productType" : 2,
    "plu" : "_REM_842",
    "price" : 0,
    "name" : "No Fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_843",
    "price" : 0,
    "name" : "No Guacomole",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_844",
    "price" : 0,
    "name" : "No Mushrooms",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_845",
    "price" : 0,
    "name" : "No Spinach Leaves  ",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_846",
    "price" : 0,
    "name" : "No Vegan aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "298",
    "price" : 2395,
    "name" : "Delta Rigg VEGAN",
    "posProductId" : "298",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_298" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_352",
    "name" : "Double Zeahorse Remove",
    "posProductId" : "352",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_869", "_REM_870", "_REM_871", "_REM_872", "_REM_873", "_REM_874", "_REM_875" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 7
  }, {
    "productType" : 2,
    "plu" : "_REM_869",
    "price" : 0,
    "name" : "No aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_870",
    "price" : 0,
    "name" : "No bacon",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_871",
    "price" : 0,
    "name" : "No Beef ",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_872",
    "price" : 0,
    "name" : "No cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_873",
    "price" : 0,
    "name" : "No fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_874",
    "price" : 0,
    "name" : "No lettuce",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_875",
    "price" : 0,
    "name" : "No relish",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "352",
    "price" : 2895,
    "name" : "Double Zeahorse",
    "posProductId" : "352",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_352" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_138",
    "name" : "Bostons Chicken Strips Remove",
    "posProductId" : "138",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_694", "_REM_693" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 2
  }, {
    "productType" : 2,
    "plu" : "_REM_694",
    "price" : 0,
    "name" : "No aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_693",
    "price" : 0,
    "name" : "No fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "138",
    "price" : 1495,
    "name" : "Bostons Chicken Strips",
    "posProductId" : "138",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_138" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_137",
    "name" : "Rafa Beef Burger Remove",
    "posProductId" : "137",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_817" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_817",
    "price" : 0,
    "name" : "No Cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "137",
    "price" : 1495,
    "name" : "Rafa Beef Burger",
    "posProductId" : "137",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_137" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_155",
    "name" : "Chuggi Chicken  Remove",
    "posProductId" : "155",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_204" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_204",
    "price" : 0,
    "name" : "No Cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "155",
    "price" : 1495,
    "name" : "Chuggi Chicken ",
    "posProductId" : "155",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_155" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_303",
    "name" : "NAKED RAFA Remove",
    "posProductId" : "303",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_841" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_841",
    "price" : 0,
    "name" : "No Cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "303",
    "price" : 1495,
    "name" : "NAKED RAFA",
    "posProductId" : "303",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_303" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_181",
    "name" : "Classic Cog NAKED Remove",
    "posProductId" : "181",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_671", "_REM_670", "_REM_672", "_REM_673", "_REM_674" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 5
  }, {
    "productType" : 2,
    "plu" : "_REM_671",
    "price" : 0,
    "name" : "No Cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_670",
    "price" : 0,
    "name" : "No Chutney",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_672",
    "price" : 0,
    "name" : "No Fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_673",
    "price" : 0,
    "name" : "No Lettuce",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_674",
    "price" : 0,
    "name" : "No Tomato Relish",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "181",
    "price" : 2195,
    "name" : "Classic Cog NAKED",
    "posProductId" : "181",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_181" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_179",
    "name" : "Trippin Zeahorse NAKED Remove",
    "posProductId" : "179",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_682", "_REM_683", "_REM_684", "_REM_685", "_REM_686", "_REM_687" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 6
  }, {
    "productType" : 2,
    "plu" : "_REM_682",
    "price" : 0,
    "name" : "No Aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_683",
    "price" : 0,
    "name" : "No Bacon",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_684",
    "price" : 0,
    "name" : "No Cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_685",
    "price" : 0,
    "name" : "No Fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_686",
    "price" : 0,
    "name" : "No Lettuce",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_687",
    "price" : 0,
    "name" : "No Tomato Relish",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "179",
    "price" : 2295,
    "name" : "Trippin Zeahorse NAKED",
    "posProductId" : "179",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_179" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_243",
    "name" : "#Bordy NAKED Remove",
    "posProductId" : "243",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_857", "_REM_858", "_REM_859", "_REM_860" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 4
  }, {
    "productType" : 2,
    "plu" : "_REM_857",
    "price" : 0,
    "name" : "No cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_858",
    "price" : 0,
    "name" : "No pickles",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_859",
    "price" : 0,
    "name" : "No tomato aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_860",
    "price" : 0,
    "name" : "No truffle aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "243",
    "price" : 2295,
    "name" : "#Bordy NAKED",
    "posProductId" : "243",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_243" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_178",
    "name" : "Vero Valentino NAKED Remove",
    "posProductId" : "178",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_908", "_REM_905", "_REM_906", "_REM_907" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 4
  }, {
    "productType" : 2,
    "plu" : "_REM_908",
    "price" : 0,
    "name" : "No coleslaw",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_905",
    "price" : 0,
    "name" : "No dill aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_906",
    "price" : 0,
    "name" : "No Fennel",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_907",
    "price" : 0,
    "name" : "No Fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "178",
    "price" : 2295,
    "name" : "Vero Valentino NAKED",
    "posProductId" : "178",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_178" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_182",
    "name" : "Just a Jezabel NAKED Remove",
    "posProductId" : "182",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_474", "_REM_470", "_REM_471", "_REM_472", "_REM_473" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 5
  }, {
    "productType" : 2,
    "plu" : "_REM_474",
    "price" : 0,
    "name" : "No aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_470",
    "price" : 0,
    "name" : "No Chicken",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_471",
    "price" : 0,
    "name" : "No Coleslaw",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_472",
    "price" : 0,
    "name" : "No Fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_473",
    "price" : 0,
    "name" : "No Guacamole",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "182",
    "price" : 2395,
    "name" : "Just a Jezabel NAKED",
    "posProductId" : "182",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_182" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_180",
    "name" : "Johnny Collide NAKED Remove",
    "posProductId" : "180",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_876", "_REM_877", "_REM_878", "_REM_879", "_REM_880", "_REM_881", "_REM_882" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 7
  }, {
    "productType" : 2,
    "plu" : "_REM_876",
    "price" : 0,
    "name" : "No Aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_877",
    "price" : 0,
    "name" : "No Cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_878",
    "price" : 0,
    "name" : "No Fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_879",
    "price" : 0,
    "name" : "No Mushrooms",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_880",
    "price" : 0,
    "name" : "No Onion Rings",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_881",
    "price" : 0,
    "name" : "No Spinach Leaves",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_882",
    "price" : 0,
    "name" : "No Tomato relish",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "180",
    "price" : 2195,
    "name" : "Johnny Collide NAKED",
    "posProductId" : "180",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_180" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_283",
    "name" : "Delta Rigg VEGAN NAKED Remove",
    "posProductId" : "283",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_852", "_REM_853", "_REM_854", "_REM_855", "_REM_856" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 5
  }, {
    "productType" : 2,
    "plu" : "_REM_852",
    "price" : 0,
    "name" : "No Aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_853",
    "price" : 0,
    "name" : "No Fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_854",
    "price" : 0,
    "name" : "No Guacomole",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_855",
    "price" : 0,
    "name" : "No Mushrooms",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_856",
    "price" : 0,
    "name" : "No Spinach Leaves",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "283",
    "price" : 2295,
    "name" : "Delta Rigg VEGAN NAKED",
    "posProductId" : "283",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_283" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_353",
    "name" : "Double Zeahorse NAKED Remove",
    "posProductId" : "353",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_909", "_REM_910", "_REM_911", "_REM_912", "_REM_915", "_REM_913", "_REM_914" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 7
  }, {
    "productType" : 2,
    "plu" : "_REM_909",
    "price" : 0,
    "name" : "No aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_910",
    "price" : 0,
    "name" : "No bacon",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_911",
    "price" : 0,
    "name" : "No beef",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_912",
    "price" : 0,
    "name" : "No cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_915",
    "price" : 0,
    "name" : "No fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_913",
    "price" : 0,
    "name" : "No lettuce",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_914",
    "price" : 0,
    "name" : "No relish",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "353",
    "price" : 2895,
    "name" : "Double Zeahorse NAKED",
    "posProductId" : "353",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_353" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "355",
    "price" : 1495,
    "name" : "Fish and Chips",
    "posProductId" : "355",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_366",
    "name" : "BOSS BURGER Remove",
    "posProductId" : "366",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_890", "_REM_891", "_REM_892", "_REM_894", "_REM_893", "_REM_895", "_REM_896" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 7
  }, {
    "productType" : 2,
    "plu" : "_REM_890",
    "price" : 0,
    "name" : "No bacon",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_891",
    "price" : 0,
    "name" : "No cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_892",
    "price" : 0,
    "name" : "No deep fried jalepenos",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_894",
    "price" : 0,
    "name" : "No fries",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_893",
    "price" : 0,
    "name" : "No pickles",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_895",
    "price" : 0,
    "name" : "No tomato aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_896",
    "price" : 0,
    "name" : "No truffle aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "366",
    "price" : 2695,
    "name" : "BOSS BURGER",
    "posProductId" : "366",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_366" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "376",
    "price" : 2395,
    "name" : "TONYS GIG",
    "posProductId" : "376",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_385",
    "name" : "PLAIN BURGER Remove",
    "posProductId" : "385",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_904" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_904",
    "price" : 0,
    "name" : "No CHEESE",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "385",
    "price" : 1500,
    "name" : "PLAIN BURGER",
    "posProductId" : "385",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_385" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "388",
    "price" : 0,
    "name" : "empty",
    "posProductId" : "388",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_REM_GR_389",
    "name" : "BOSS NAKED Remove",
    "posProductId" : "389",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_REM_916", "_REM_917", "_REM_918", "_REM_919", "_REM_920" ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 5
  }, {
    "productType" : 2,
    "plu" : "_REM_916",
    "price" : 0,
    "name" : "No cheese",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_917",
    "price" : 0,
    "name" : "No Jalepenos",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_918",
    "price" : 0,
    "name" : "No pickles",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_919",
    "price" : 0,
    "name" : "No tomato aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 2,
    "plu" : "_REM_920",
    "price" : 0,
    "name" : "No truffle aioli",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ],
    "min" : 0,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "389",
    "price" : 2695,
    "name" : "BOSS NAKED",
    "posProductId" : "389",
    "posCategoryIds" : [ "3" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6", "_REM_GR_389" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_VAR_93",
    "name" : "SPARKILNG WINE Size",
    "posCategoryIds" : [ ],
    "isVariantGroup" : true,
    "subProducts" : [ "121", "122" ],
    "productTags" : [ ],
    "min" : 1,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "_ITEM_93",
    "price" : 0,
    "name" : "SPARKILNG WINE",
    "posCategoryIds" : [ "15" ],
    "isVariant" : true,
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_VAR_93" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "121",
    "price" : 1600,
    "name" : "SPARKILNG WINE(Glass)",
    "posProductId" : "121",
    "posCategoryIds" : [ "15" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "122",
    "price" : 7000,
    "name" : "SPARKILNG WINE(Bottle)",
    "posProductId" : "122",
    "posCategoryIds" : [ "15" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_VAR_90",
    "name" : "ORANGE WINE Size",
    "posCategoryIds" : [ ],
    "isVariantGroup" : true,
    "subProducts" : [ "115", "116" ],
    "productTags" : [ ],
    "min" : 1,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "_ITEM_90",
    "price" : 0,
    "name" : "ORANGE WINE",
    "posCategoryIds" : [ "11" ],
    "isVariant" : true,
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_VAR_90" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "115",
    "price" : 1400,
    "name" : "ORANGE WINE(Glass)",
    "posProductId" : "115",
    "posCategoryIds" : [ "11" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_OPT_GR_0_0_4",
    "name" : "Wine Glasses(Btl)",
    "posProductId" : "4",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_OPT_0_88", "_OPT_0_85", "_OPT_0_82", "_OPT_0_86", "_OPT_0_83", "_OPT_0_87", "_OPT_0_84" ],
    "productTags" : [ ],
    "min" : 0
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_88",
    "price" : 0,
    "name" : "1 Glass",
    "posProductId" : "88",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_85",
    "price" : 0,
    "name" : "2 Glasses",
    "posProductId" : "85",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_82",
    "price" : 0,
    "name" : "3 Glasses",
    "posProductId" : "82",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_86",
    "price" : 0,
    "name" : "4 Glasses",
    "posProductId" : "86",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_83",
    "price" : 0,
    "name" : "5 Glasses",
    "posProductId" : "83",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_87",
    "price" : 0,
    "name" : "6 Glasses",
    "posProductId" : "87",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_84",
    "price" : 0,
    "name" : "NO Glass",
    "posProductId" : "84",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "116",
    "price" : 6500,
    "name" : "ORANGE WINE(Bottle)",
    "posProductId" : "116",
    "posCategoryIds" : [ "11" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_4" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_VAR_89",
    "name" : "PINOT GRIS Size",
    "posCategoryIds" : [ ],
    "isVariantGroup" : true,
    "subProducts" : [ "113", "114" ],
    "productTags" : [ ],
    "min" : 1,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "_ITEM_89",
    "price" : 0,
    "name" : "PINOT GRIS",
    "posCategoryIds" : [ "11" ],
    "isVariant" : true,
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_VAR_89" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "113",
    "price" : 1400,
    "name" : "PINOT GRIS(Glass)",
    "posProductId" : "113",
    "posCategoryIds" : [ "11" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "114",
    "price" : 6500,
    "name" : "PINOT GRIS(Bottle)",
    "posProductId" : "114",
    "posCategoryIds" : [ "11" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_4" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_VAR_92",
    "name" : "ROSE Size",
    "posCategoryIds" : [ ],
    "isVariantGroup" : true,
    "subProducts" : [ "119", "120" ],
    "productTags" : [ ],
    "min" : 1,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "_ITEM_92",
    "price" : 0,
    "name" : "ROSE",
    "posCategoryIds" : [ "16" ],
    "isVariant" : true,
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_VAR_92" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "119",
    "price" : 1200,
    "name" : "ROSE(Glass)",
    "posProductId" : "119",
    "posCategoryIds" : [ "16" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "120",
    "price" : 6500,
    "name" : "ROSE(Bottle)",
    "posProductId" : "120",
    "posCategoryIds" : [ "16" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_4" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_VAR_86",
    "name" : " PINOT NOIR Size",
    "posCategoryIds" : [ ],
    "isVariantGroup" : true,
    "subProducts" : [ "107", "108" ],
    "productTags" : [ ],
    "min" : 1,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "_ITEM_86",
    "price" : 0,
    "name" : " PINOT NOIR",
    "posCategoryIds" : [ "10" ],
    "isVariant" : true,
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_VAR_86" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "107",
    "price" : 1400,
    "name" : " PINOT NOIR(Glass)",
    "posProductId" : "107",
    "posCategoryIds" : [ "10" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "108",
    "price" : 6500,
    "name" : " PINOT NOIR(Bottle)",
    "posProductId" : "108",
    "posCategoryIds" : [ "10" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_4" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_VAR_87",
    "name" : "SHIRAZ Size",
    "posCategoryIds" : [ ],
    "isVariantGroup" : true,
    "subProducts" : [ "109", "110" ],
    "productTags" : [ ],
    "min" : 1,
    "max" : 1
  }, {
    "productType" : 1,
    "plu" : "_ITEM_87",
    "price" : 0,
    "name" : "SHIRAZ",
    "posCategoryIds" : [ "10" ],
    "isVariant" : true,
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_VAR_87" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "109",
    "price" : 1500,
    "name" : "SHIRAZ(Glass)",
    "posProductId" : "109",
    "posCategoryIds" : [ "10" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "110",
    "price" : 6500,
    "name" : "SHIRAZ(Bottle)",
    "posProductId" : "110",
    "posCategoryIds" : [ "10" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_4" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_OPT_GR_0_0_2",
    "name" : "Mixers(Gl)",
    "posProductId" : "2",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_OPT_0_39", "_OPT_0_58", "_OPT_0_43", "_OPT_0_59", "_OPT_0_61", "_OPT_0_90", "_OPT_0_37", "_OPT_0_46", "_OPT_0_55", "_OPT_0_56", "_OPT_0_101", "_OPT_0_100", "_OPT_0_113", "_OPT_0_105", "_OPT_0_99", "_OPT_0_104", "_OPT_0_102", "_OPT_0_107", "_OPT_0_106", "_OPT_0_103", "_OPT_0_109", "_OPT_0_108", "_OPT_0_40" ],
    "productTags" : [ ],
    "min" : 0
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_39",
    "price" : 0,
    "name" : "Karma cola",
    "posProductId" : "39",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_58",
    "price" : 0,
    "name" : "Soda",
    "posProductId" : "58",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_43",
    "price" : 0,
    "name" : "Gingerella Ginger Ale",
    "posProductId" : "43",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_59",
    "price" : 0,
    "name" : "Lemmy Lemonade",
    "posProductId" : "59",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_61",
    "price" : 0,
    "name" : "Tonic",
    "posProductId" : "61",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_90",
    "price" : 0,
    "name" : "Bundaberg Ginger Beer",
    "posProductId" : "90",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_37",
    "price" : 0,
    "name" : "Fresh Apple Juice",
    "posProductId" : "37",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_46",
    "price" : 0,
    "name" : "Lemon Lime Bitters",
    "posProductId" : "46",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_55",
    "price" : 0,
    "name" : "Orange Juice",
    "posProductId" : "55",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_56",
    "price" : 0,
    "name" : "Pineapple Juice",
    "posProductId" : "56",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_101",
    "price" : 0,
    "name" : "1 Ice Cube",
    "posProductId" : "101",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_100",
    "price" : 0,
    "name" : "2 Ice Cube",
    "posProductId" : "100",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_113",
    "price" : 0,
    "name" : "As a shot",
    "posProductId" : "113",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_105",
    "price" : 0,
    "name" : "Little Water",
    "posProductId" : "105",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_99",
    "price" : 0,
    "name" : "Lots Ice",
    "posProductId" : "99",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_104",
    "price" : 0,
    "name" : "Neat",
    "posProductId" : "104",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_102",
    "price" : 0,
    "name" : "No Ice",
    "posProductId" : "102",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_107",
    "price" : 0,
    "name" : "On the Rocks",
    "posProductId" : "107",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_106",
    "price" : 0,
    "name" : "Slice Lemon",
    "posProductId" : "106",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_103",
    "price" : 0,
    "name" : "Slice Lime",
    "posProductId" : "103",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_109",
    "price" : 0,
    "name" : "Slice Orange",
    "posProductId" : "109",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_108",
    "price" : 0,
    "name" : "Tall Glass",
    "posProductId" : "108",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_40",
    "price" : 0,
    "name" : "Cranberry Juice",
    "posProductId" : "40",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "86",
    "price" : 1050,
    "name" : "VODKA",
    "posProductId" : "86",
    "posCategoryIds" : [ "8" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_2", "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "87",
    "price" : 1050,
    "name" : "GIN",
    "posProductId" : "87",
    "posCategoryIds" : [ "8" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_2", "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "94",
    "price" : 1050,
    "name" : "JACK DANIELS",
    "posProductId" : "94",
    "posCategoryIds" : [ "8" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_2", "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "93",
    "price" : 1050,
    "name" : "SAILOR JERRY RUM",
    "posProductId" : "93",
    "posCategoryIds" : [ "8" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_2", "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "92",
    "price" : 1050,
    "name" : "JAMEISON WHISKEY",
    "posProductId" : "92",
    "posCategoryIds" : [ "8" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_2", "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "95",
    "price" : 1050,
    "name" : "TEQUILA",
    "posProductId" : "95",
    "posCategoryIds" : [ "8" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_2", "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "167",
    "price" : 1000,
    "name" : "CAMPARI",
    "posProductId" : "167",
    "posCategoryIds" : [ "8" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "294",
    "price" : 1000,
    "name" : "APEROL",
    "posProductId" : "294",
    "posCategoryIds" : [ "8" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "350",
    "price" : 900,
    "name" : "FIREBALL SHOT",
    "posProductId" : "350",
    "posCategoryIds" : [ "8" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "362",
    "price" : 700,
    "name" : "MARGIE SHOT",
    "posProductId" : "362",
    "posCategoryIds" : [ "8" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_OPT_GR_0_0_8",
    "name" : "Margarita(Serve)",
    "posProductId" : "8",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_OPT_0_112" ],
    "productTags" : [ ],
    "min" : 0
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_112",
    "price" : 0,
    "name" : "No Salt",
    "posProductId" : "112",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "103",
    "price" : 1500,
    "name" : "Margarita",
    "posProductId" : "103",
    "posCategoryIds" : [ "9" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_8", "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 3,
    "plu" : "_OPT_GR_0_0_7",
    "name" : "Bloody Mary(Serve)",
    "posProductId" : "7",
    "posCategoryIds" : [ ],
    "subProducts" : [ "_OPT_0_110", "_OPT_0_114", "_OPT_0_111", "_OPT_0_115" ],
    "productTags" : [ ],
    "min" : 0
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_110",
    "price" : 0,
    "name" : "Mild Spice",
    "posProductId" : "110",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_114",
    "price" : 0,
    "name" : "no bacon",
    "posProductId" : "114",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_111",
    "price" : 0,
    "name" : "Spicy",
    "posProductId" : "111",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 2,
    "plu" : "_OPT_0_115",
    "price" : 0,
    "name" : "with bacon",
    "posProductId" : "115",
    "posCategoryIds" : [ ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "104",
    "price" : 2000,
    "name" : "BT's Bloody Mary",
    "posProductId" : "104",
    "posCategoryIds" : [ "9" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_OPT_GR_0_0_7", "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "106",
    "price" : 1900,
    "name" : "Stormy Cargo",
    "posProductId" : "106",
    "posCategoryIds" : [ "9" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "105",
    "price" : 1800,
    "name" : "Abbeys Aperol Spritz",
    "posProductId" : "105",
    "posCategoryIds" : [ "9" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "102",
    "price" : 1800,
    "name" : "Toni  Negroni",
    "posProductId" : "102",
    "posCategoryIds" : [ "9" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "369",
    "price" : 5900,
    "name" : "$55 Margie",
    "posProductId" : "369",
    "posCategoryIds" : [ "9" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "78",
    "price" : 1100,
    "name" : "YH  PALE ALE",
    "posProductId" : "78",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "77",
    "price" : 1100,
    "name" : "YH LAGER",
    "posProductId" : "77",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "84",
    "price" : 990,
    "name" : "BEACH BEER BONDI",
    "posProductId" : "84",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "234",
    "price" : 990,
    "name" : "YH CIDER",
    "posProductId" : "234",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "356",
    "price" : 990,
    "name" : "YH IPA CAN",
    "posProductId" : "356",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "363",
    "price" : 990,
    "name" : "GRIFTER MELON",
    "posProductId" : "363",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "361",
    "price" : 990,
    "name" : "GRIFTER ALE",
    "posProductId" : "361",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "82",
    "price" : 790,
    "name" : "YH STAYER",
    "posProductId" : "82",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "377",
    "price" : 990,
    "name" : "CURLY LEWIS",
    "posProductId" : "377",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "378",
    "price" : 1000,
    "name" : "STONE AND WOOD",
    "posProductId" : "378",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "381",
    "price" : 700,
    "name" : "HEAPS NORMAL",
    "posProductId" : "381",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "384",
    "price" : 990,
    "name" : "GINGER BEER ALCOHOLIC",
    "posProductId" : "384",
    "posCategoryIds" : [ "7" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_5" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "237",
    "price" : 650,
    "name" : "BERRY KOMBUCHA",
    "posProductId" : "237",
    "posCategoryIds" : [ "5" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "233",
    "price" : 650,
    "name" : "GINGER KOMBUCHA",
    "posProductId" : "233",
    "posCategoryIds" : [ "5" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "69",
    "price" : 650,
    "name" : "LEMONADE",
    "posProductId" : "69",
    "posCategoryIds" : [ "5" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "67",
    "price" : 650,
    "name" : "COLA",
    "posProductId" : "67",
    "posCategoryIds" : [ "5" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "73",
    "price" : 650,
    "name" : "GINGER BEER",
    "posProductId" : "73",
    "posCategoryIds" : [ "5" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "288",
    "price" : 650,
    "name" : "SUGAR FREE COLA",
    "posProductId" : "288",
    "posCategoryIds" : [ "5" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "130",
    "price" : 650,
    "name" : "ORANGE JUICE ",
    "posProductId" : "130",
    "posCategoryIds" : [ "5" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "149",
    "price" : 500,
    "name" : "Moda Sparkling 750ml",
    "posProductId" : "149",
    "posCategoryIds" : [ "5" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "244",
    "price" : 750,
    "name" : "S Pelegrinno 500ml",
    "posProductId" : "244",
    "posCategoryIds" : [ "5" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "157",
    "price" : 650,
    "name" : "Lemon Lime Bitters",
    "posProductId" : "157",
    "posCategoryIds" : [ "5" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "284",
    "price" : 1495,
    "name" : "Gerards Chicken Bites ",
    "posProductId" : "284",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "293",
    "price" : 1495,
    "name" : "Gerards Spicy Chicken Bites",
    "posProductId" : "293",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "196",
    "price" : 1495,
    "name" : "BBQ WINGS",
    "posProductId" : "196",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "195",
    "price" : 1495,
    "name" : "BUFFALO WINGS",
    "posProductId" : "195",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "136",
    "price" : 990,
    "name" : "Super Crunch fries w aioli",
    "posProductId" : "136",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "207",
    "price" : 1190,
    "name" : "gravy loaded fries",
    "posProductId" : "207",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "60",
    "price" : 1090,
    "name" : "Sweet Potato Fries w aiolil",
    "posProductId" : "60",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "147",
    "price" : 200,
    "name" : "Aioli",
    "posProductId" : "147",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "150",
    "price" : 1495,
    "name" : "Onion Rings",
    "posProductId" : "150",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "291",
    "price" : 300,
    "name" : "Truffle  aioli",
    "posProductId" : "291",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "62",
    "price" : 790,
    "name" : "House Made Coleslaw SALAD",
    "posProductId" : "62",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "176",
    "price" : 500,
    "name" : "Gravy",
    "posProductId" : "176",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "269",
    "price" : 1050,
    "name" : "staff chicken pattie",
    "posProductId" : "269",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "270",
    "price" : 720,
    "name" : "staff meat pattie",
    "posProductId" : "270",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "268",
    "price" : 1050,
    "name" : "staff fish pattie",
    "posProductId" : "268",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "271",
    "price" : 200,
    "name" : "staff bacon",
    "posProductId" : "271",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "290",
    "price" : 300,
    "name" : "staff eggs",
    "posProductId" : "290",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "292",
    "price" : 400,
    "name" : "staff Vege pattie",
    "posProductId" : "292",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "289",
    "price" : 0,
    "name" : "OPEN FOOD ",
    "posProductId" : "289",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "371",
    "price" : 400,
    "name" : "staff V2 Pattie",
    "posProductId" : "371",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "372",
    "price" : 300,
    "name" : "BUN",
    "posProductId" : "372",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "373",
    "price" : 500,
    "name" : "VEGAN BUN",
    "posProductId" : "373",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "382",
    "price" : 200,
    "name" : "TOMATO SAUCE",
    "posProductId" : "382",
    "posCategoryIds" : [ "4" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ "_ADD_GR_6" ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "262",
    "price" : 500,
    "name" : "FOOD  WASTAGE",
    "posProductId" : "262",
    "posCategoryIds" : [ "17" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "263",
    "price" : 500,
    "name" : "BEER   WASTAGE ",
    "posProductId" : "263",
    "posCategoryIds" : [ "17" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "281",
    "price" : 450,
    "name" : "WINE  WASTAGE",
    "posProductId" : "281",
    "posCategoryIds" : [ "17" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "347",
    "price" : 300,
    "name" : "SOFT DRINK WASTAGE",
    "posProductId" : "347",
    "posCategoryIds" : [ "17" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "379",
    "price" : 3500,
    "name" : "Cap",
    "posProductId" : "379",
    "posCategoryIds" : [ "21" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "387",
    "price" : 7500,
    "name" : "Hoodie / cew neck jumper",
    "posProductId" : "387",
    "posCategoryIds" : [ "21" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  }, {
    "productType" : 1,
    "plu" : "380",
    "price" : 4500,
    "name" : "T Shirt",
    "posProductId" : "380",
    "posCategoryIds" : [ "21" ],
    "deliveryTax" : 10000,
    "takeawayTax" : 10000,
    "subProducts" : [ ],
    "productTags" : [ ]
  } ],
  "categories" : [ {
    "name" : "Burgers",
    "posCategoryId" : "3"
  }, {
    "name" : "Alcohol",
    "posCategoryId" : "6"
  }, {
    "name" : "Sparkling",
    "posCategoryId" : "15"
  }, {
    "name" : "White / Orange Wine",
    "posCategoryId" : "11"
  }, {
    "name" : "Rose",
    "posCategoryId" : "16"
  }, {
    "name" : "Red Wine",
    "posCategoryId" : "10"
  }, {
    "name" : "Spirits",
    "posCategoryId" : "8"
  }, {
    "name" : "Cocktail",
    "posCategoryId" : "9"
  }, {
    "name" : "Beer & Cider",
    "posCategoryId" : "7"
  }, {
    "name" : "Soft Drinks",
    "posCategoryId" : "5"
  }, {
    "name" : "Tasty Sides",
    "posCategoryId" : "4"
  }, {
    "name" : "Wastage ",
    "posCategoryId" : "17"
  }, {
    "name" : "Merch",
    "posCategoryId" : "21"
  } ]
}
headers = {
    "accept": "application/json",
    "content-type": "application/json"
}

response = requests.post(url, json=payload, headers=headers)

print(response.text)