businesNames = ["South Dowling Sandwiches Alexandria",
"Blackbird & Co",
"Krunch Cafe & Catering Alexandria",
"Notaras Fish Markets Alexandria",
"Khamsa Cafe",
"Al Aseel Restaurant",
"Crust",
"Nutrition Station Alexandria",
"The Pan Cafe",
"Torotoro Ramen Bar",
"Blackbird Cafe",
"The Captains Balcony",
"Banh Meats & Co",
"Ume Burger",
"Pavel & Co",
"Spiced by Billu's",
"Adano's Grill",
"Ipoh Town",
"Iron Grill",
"Lal Qila Darling Harbour",
"Luxe Barangaroo",
"Silverbeet",
"Sneakies Barangaroo",
"Subway",
"Sushi Hub Kent Street",
"Thai Connection",
"The Bavarian York St.",
"Winghaus Barangaroo",
"Delhi Palace Indian Cuisine",
"Max Brenner Chocolate Bar",
"RaRa Ramen Randwick",
"Okami Japanese Restaurant",
"Tripoli Pizza",
"Fluid Espresso",
"Kathmandu Palace",
"Lokha Cafe",
"Pizza Hut Riverwood",
"Yummy Duck BBQ",
"The Gardener's Grill",
"Emma's Snack Bar",
"Nelson's Nest",
"Gather On The Green",
"Happy Campa",
"INDIAN CURRY CLUB",
"Pappa's Stew Chilli Cuisine Newtown",
"R cafe & restaurant",
"Sushi Train Newtown",
"Vina Vegan Restaurant",
"Killiney Kopitiam",
"Manny's Pizza Diner",
"Lukumades Chippendale",
"Holy Duck!",
"Alex Lee Kitchen",
"City Mart",
"Eve's Bar",
"Flying Saucer Vegan Pizza",
"Griddle King 小零煎餅",
"Kyo-to",
"Olio Kensington Street",
"Shanghai Dumpling Bar",
"The Lord Gladstone Hotel",
"Viet",
"South Dowling Sandwiches",
"Bootsdarling",
"Ovo Cafe",
"Kindness Vegan",
"Bill & Toni Italian Restaurant",
"BL Burgers",
"Gino's Kitchen & Cocktails: Darlinghurst",
"The Mayflower",
"Bar Reggio",
"Bat Bun",
"Big Daddy's Burger Bar",
"Black Squid & Co",
"Don Don",
"Dumplings & Beer Stanley Street",
"Eat Fuh",
"Eat Thai",
"Hiroya Japanese Restaurant",
"Jamie's Kitchen, Darlinghurst Sydney",
"Neko Darlinghurst",
"North Indian Cuisine",
"Ogalo Darlinghurst Oxford street",
"Phamish Vietnamese Restaurant",
"Philly Up Darlinghurst",
"Philosophy Cafe",
"Rivareno Gelato",
"Sandoitchi Cafe",
"Soi 25 Restaurant and Bar",
"Sushi Train Oxford",
"Thai Tharee",
"Una's",
"Wings And Tins",
"Italian Bar",
"ARRIN",
"Kirribilli Woodfire Kitchen",
"Blues Point Gourmet Pizzas",
"Grace of India Restaurant Sydney",
"Piato Restaurant",
"Sushi Hub Wintergarden",
"Zinger Taj Indian Restaurant",
"Melo's Italian",
"The Best Noodle",
"The Canopy",
"Atom Thai Restaurant",
"Rose of Australia",
"La Favola - Authentic Italian Newtown",
"RaRa",
"Loaded by BL",
"Brewtown Newtown",
"Brickfields Chippendale",
"Hoochie Mamma Cafe",
"Newtown North Indian Diner",
"Henry Lee's Redfern",
"Cafe 0.6",
"La Grillade",
"BEKYA South Eveleigh",
"Bambino Torino Newtown",
"Andiamo Trattoria Chippendale",
"Angry Tony's Pizza and Liquor Delivery",
"Big Daddy’s Burger Bar",
"Chapter Five Espresso",
"Charles Thai",
"Chicky Char Char Alexandria",
"Chinese North Dumpling Noodle House",
"Eat Fuh",
"Golden Fang Restaurant",
"Hanoi on King Newtown",
"Kammadhenu",
"Khao Yum Thai",
"Lit Canteen",
"Little MOMO",
"Maggie's Thai",
"Naked Brew",
"North's Sandwiches (South Eveleigh)",
"OZ Turk Jnr Darlington",
"Pepper Seeds South Eveleigh",
"Photown",
"Shenkin Erskineville",
"Sliced Detroit Pizza Newtown",
"Soul Burger - Newtown",
"Steve Costi's Famous Fish",
"Subway",
"Sushi Jones",
"Sushi Topia",
"Thai Riffic Newtown",
"The Grumpy Barista",
"The Italian Bowl",
"The milk bar by Cafeish",
"Tre Viet Restaurant Newtown",
"Went to See the Gypsy",
"Yellow Fever",
"Yum Yai",
"Baja Cantina",
"Frank's Pizza Bar Restaurant",
"Urban Pizza Bar",
"Bellevue Cottage By Antoine",
"Hannibal Lebanese Restaurant",
"China Diner Tramsheds",
"Descanso",
"Fez & Co",
"Green Mushroom",
"Nithik's Kitchen",
"Palle The Meatball Joint",
"Fish and Co - Tramsheds",
"Kandy by Sri Lankan Bites",
"Belles Hot Chicken Tramsheds",
"Bion Societe Cafe",
"Chim Cham Cafe",
"Forest Lodge Cafe",
"Hikaru Japanese Courtyard Restaurant",
"Hong Li - Red Sui Mei Cantonese Restaurant 江茘烧味",
"Izakaya Shogun",
"Nando's Camperdown",
"Nawaz Flavour of India",
"Open Korea",
"Osaka Trading Co.",
"Papaya Thai Eatery & Cafe",
"Pizza Da Noi",
"Pizze Baby",
"Pizzeria Da Alfredo",
"Ralph's Cafe",
"Roll’d Tramsheds",
"Soul Burger - Glebe",
"Sushi Gen",
"Flying Fajita Sistas",
"Esca",
"Arthur's Pizza Glebe",
"Grandma's Laksa House",
"Kebabs on Glebe",
"Lokanta",
"Long Piano Dining",
"Madame Frou Frou",
"Otto Noorba",
"Schnitz Broadway",
"Sri Lankan Street Food",
"Thai On Wok",
"The Pharaoh BBQ",
"The Spot",
"85 Degrees Cafe",
"Nine Dragons",
"Arisun Chinatown",
"Krispy Kreme Central",
"Thanon Khaosan",
"Kürtősh - Darling Square",
"Super Chef BBQ",
"The Sandwich Shop",
"Yok Yor Thai Food Factory",
"YOD",
"Tawandang",
"Kumadon Haymarket",
"YX Mini Hot Pot Haymarket",
"@Bangkok",
"A Bowl Of Noodles",
"Boon Cafe",
"Bu Cha Qian BBQ 千园烤吧",
"Chambers Fine Coffee Haymarket",
"Chefs Gallery Town Hall",
"Chinatown Noodle Restaurant 北方拉面馆",
"Chinese Noodle House",
"Chon Siam Thai Restaurant",
"Chungking Malatang",
"Emperor's Garden B.B.Q. & Noodles",
"Gloria Jean's Coffees Haymarket",
"Goobne Chicken",
"Happy Chef Noodle Bar",
"Lilong by Taste of Shanghai (Darling Square)",
"Little Hunan",
"Mary's",
"Masuya Suisan",
"Mogu Mogu Oz",
"MR Hot Dog Haymarket",
"Nan Yang Tea Club",
"New Chilli House",
"Nua Lao Thai",
"Pancakes on the Rocks",
"Pho Gia Hoi",
"Pho Pasteur",
"ROBO",
"Show Neua Thai Street Food",
"Spago Darling Square",
"Storehouse Sydney Central Cafe and Bar",
"Subway",
"Sunflower Taiwanese Gourmet, Haymarket",
"Super Bowl Chinese Restaurant",
"Taste of Lan",
"Xi An Cuisine",
"XOPP by Golden Century",
"Yummy One",
"Muum Maam Barangaroo",
"The Bund - Walsh Bay",
"Meat District Co",
"City Extra Restaurant",
"Jounieh Walsh Bay",
"Lotus Barangaroo",
"Azzurro 753",
"The Spice Room",
"Bitter & Twisted Cafe",
"Casa Del Vino",
"Dumpling Bar Restaurant on Kent 北海私房菜",
"Sanduba",
"Zupano Espresso_Bar",
"Black Ginger Restaurant",
"Buddha Bowl Cafe",
"Cocina del Barrio",
"Calle Rey",
"Golden Lotus Vegan Newtown",
"Pistou",
"Coopers Hotel",
"Flying Tong Newtown",
"Madame Nhu Enmore Newtown",
"Pasha's Restaurant",
"Rising Sun Workshop",
"Taste of Turkey",
"The Midnight Special",
"Delhi 'O' Delhi",
"The Pie Tin Newtown",
"Alberto's Pizzeria",
"Saigon Summer Newtown",
"Thai La Ong - Newtown",
"The Stinking Bishops",
"Arabella Lebanese Restaurant",
"Baba Wu's Dumpling Hut (Newtown)",
"Bangkok Bites",
"Belly Bao",
"Best Gourmet Restaurant Newtown",
"Big Daddy's Burger Bar",
"Cafe Newtown",
"Chicken Shop Newtown",
"Chinese Dumpling Master",
"Cordial",
"Dean's Diner",
"Delish Pork Roll & Juice Bar Newtown",
"Don Rodney's",
"Doytao Thai",
"Dumpling King Chinese Restaurant Newtown",
"Exotik Latin",
"Ferah Cafe and Restaurant",
"Gnocchi Gnocchi Brothers, Newtown",
"I Should Be Souvlaki",
"It's Time for Thai",
"La Ricetta Ristorante Italiano Enmore",
"Lord of the Fries",
"Macelleria Newtown",
"Miyama Japanese Kitchen Newtown",
"Mr Yeeros Newtown",
"Ogalo Newtown",
"Osteria di Russo & Russo Enmore",
"Pastizzi Cafe",
"Patisserie Petunia",
"Queen Chow Enmore",
"Rosso Antico Pizza Bar Newtown",
"Saray Turkish Pizza and Kebabs Newtown",
"Shenkin Enmore",
"Sydney Cebu Lechon Native Filipino Restaurant",
"Tandoori Express Newtown",
"Tandoori Hut Newtown",
"The Drunk Dumpling",
"Thirsty Bird Newtown",
"Vandal Taqueria, Sydney",
"Llankelly Thai",
"Glider Garden - Asian Bar & Restaurant",
"Good Pho Mi",
"Kings Cross Distillery",
"Lola Tapas Bar Potts Point",
"Rocketboy Pizza Potts Point",
"Rustic French Bistro",
"Small's Deli",
"SUNDAY Potts Point",
"Bayswater Bru",
"Coffee, Tea & Me",
"Dumpling and Noodle House",
"EAT FUH",
"Mad Pizza E Bar Potts Point Pronto",
"Melted Monster",
"Plateia Where Friends Meet",
"Pyrmont Thai",
"I Love Pizza Pyrmont",
"La Verita Cafe Pyrmont",
"KKO KKO Balinese Chicken",
"Manjits Wharf",
"The Laneway Pyrmont",
"Ministry Of Coffee.",
"1877 Wine Bar & Espresso",
"Adanos Grill",
"Big Mouth Cafe Pyrmont",
"Birdy's",
"Crust Pizza Pyrmont",
"Din Tai Fung The Star",
"Dkstation Vietnamese Street Eats",
"Gojima",
"Ikhwan Cafe Sydney",
"Jumbo Thai",
"Kura Pyrmont",
"Lemongrass Takrai",
"Madame Lynn",
"Obunmee",
"Pancakes on the Rocks Darling Harbour",
"Rice & Curry Thaifood Thai Restaurant",
"Ryan Cafe",
"The Darling Pizzeria",
"The Italian Style Pizza And Pasta",
"Wok Station Pyrmont",
"Yolo & Co Pyrmont",
"Kinhboy",
"Pitsa Gourmet Bar",
"Banh Xeo Bar",
"Rosebery Kebab House",
"Adamo's Pasta",
"Pholosophy",
"Ippuku",
"Luxe Rosebery",
"Sub-Station Cafe Rosebery",
"Absurd Bird (Rosebery)",
"Arthur's Pizza Rosebery",
"ATE 5",
"Bangkok on Botany",
"Buku Eatery Cafe",
"China Blue",
"Crystal Lake Chinese Restaurant",
"D'Vine Licensed Cafe",
"Finger Lick'n Hayes Chix",
"Hot Dish",
"Me & Missy Cafe",
"Mega Gyros Rosebery",
"My Delight Traditional Indonesian Kitchen",
"Nash - Big Brother Burgers",
"O'le Rosebery",
"On Dalmeny",
"Phed Phed Thai",
"Rich Lee Hot Pot 李富贵外卖火锅",
"Rose Borek",
"Seasoning Thai",
"Slurp Slurp Noodle",
"Subway",
"Sushi Train Rosebery",
"To Thai For",
"3 Seasons Thai Fusion Cuisine",
"Busshari Authentic Japanese Restaurant",
"Cafe C&M (Rushcutters Bay)",
"Cafe Black Bay",
"La Bomba",
"The Colonial British Indian Restaurant Darlinghurst",
"Flavour of India Edgecliff",
"Bei Amici Modern Italian Restaurant",
"Cho Cho San",
"Fei Jai",
"Flybridge cafe",
"Glider Cafe",
"Figo",
"Maggie's Potts Point Restaurant",
"The Navy Bear",
"Caffè Roma",
"Gypsy Espresso | Potts Point",
"Little Jean",
"Vic's Pizzeria",
"Shuk Elizabeth Bay",
"Sonora Potts Point",
"Ezra",
"Tropicana Caffe",
"Bang Tang Potts Point",
"Room Ten",
"Machiavelli",
"Nung Len",
"Bella Vita",
"Best Five Star Kebabs",
"Dumplings & Beer",
"Elements Bar and Grill Darlinghurst",
"Fratelli Paradiso",
"Friggitoria",
"Harry's Café de Wheels - Woolloomooloo",
"Indian Masala Food",
"LOT 19 Cafe",
"Mad Pizza E Bar",
"Malabar South Indian Restaurant",
"Marta Osteria",
"Pad Thai Chai Yo",
"Pizza Hut Potts Point",
"Subway",
"Thai Power",
"The Apollo Restaurant",
"The Lookout",
"Thirsty Bird",
"Wadi Rum Sydney International Cuisine",
"Paramount Coffee Project",
"Alchemy Polish Cafe Restaurant",
"Maya Da Dhaba",
"Bad Mama",
"Shwarmama",
"Butter Surry Hills",
"Cook & Archies",
"Don't Tell Aunty",
"Evening Star Hotel",
"Foreign Return Kitchen & Bar",
"Khôi’s",
"Le Monde Cafe",
"Lumiere Cafe.",
"Madame Nhu Crown",
"Madame Nhu Surry Hills",
"Xage Vietnamese",
"Mark And Vinny's",
"Masala Theory",
"Rk San",
"Student Biryani Surry hills",
"Suzie Q Coffee & Records",
"Toast Cafe",
"TOKKI",
"Tokyo Bird",
"Zahli - Modern Middle Eastern Restaurant",
"La Panchina",
"Abdul’s Restaurant",
"Spice I Am",
"Saigon Summer Surry Hills",
"Two Good Eggs Cafe",
"Viet Eatery",
"Al Taglio",
"Al-Rayyan- Halal Indian Restaurant Surry Hills",
"City Edge Cafe",
"D.O.C. Pizza",
"Din Din Persian Kitchen",
"Frothy",
"Golden Pide",
"Himalaya Pakistani Indian Restaurant Surry Hills",
"I am Siam",
"Izakaya Fujiyama",
"Kawa",
"Kebabs on Cleveland",
"Lal Qila Restaurant",
"Lucky Pickle",
"Mega Gyros Surry Hills",
"Mexican Burrito Cantina",
"Mohr Fish",
"Noodle Star",
"Pepper Pizza Surry Hills",
"SpiceHub",
"Surry Hills Dumplings by Baba Wu",
"Sushi Train",
"Suzuya",
"Tentaciones Latin Restaurant",
"The Dolphin Hotel",
"Top's Kitchen",
"Wandee Thai Restaurant",
"Costi's Fish & Chips Barangaroo",
"Skyros Greek Meze - Greek Restaurant in Sydney",
"Gold Class Daruma",
"The Grand Palace - Indian Restaurant",
"CLEM'S",
"Hurricane's Grill Circular Quay",
"Casa Ristorante Italiano",
"Burgers Anonymous",
"The Sambal",
"Caffe Amici",
"Criniti's Darling Harbour",
"Danjee Korean Restaurant",
"District Brasserie",
"Nazimi",
"Lok Lok Dumpling Bar",
"Palace Chinese Restaurant",
"Sky Phoenix",
"Planar Restaurant",
"Ragu Pasta & Wine Bar",
"Vizio Caffé e Cucina",
"Zaaffran",
"Mejico Restaurant",
"Gözleme King",
"Bambini Trust",
"Bar Luca",
"Benbry Burgers Manly",
"Betty's Burgers",
"Blue Fish Sydney Seafood Restaurant",
"condor japanese restaurant",
"Din Tai Fung Sydney Westfield",
"Din Tai Fung World Square Restaurant",
"Feedwell Catering Sydney",
"Fish on Fire",
"Gami Chicken & Beer",
"Ho Jiak Haymarket",
"Home Thai",
"Hot Star Large Fried Chicken",
"Ichi-ban Boshi",
"Ipoh town On York",
"IZAKAYA Masuya",
"Lucio Pizzeria",
"Mr Crackles",
"Nok Nok Thai Eating House",
"Pablo's Charcoal Chicken & Ribs",
"Pompei's",
"Red Chilli Sichuan Restaurant",
"Ribs & Burgers Chippendale",
"Ribs & Burgers The Rocks",
"Sushi Hub Town Hall",
"Vapiano King Street",
"Via Napoli Pizzeria - Lane Cove",
"YAYOI Galeries",
"Lotus Dumpling Bar Walsh Bay",
"Taste on the Rocks",
"Caminetto Italian Restaurant and Pizzeria",
"Creperie Suzette",
"Munich Brauhaus The Rocks",
"Pancakes On The Rocks",
"At home thai cuisine",
"Brainwave Cafe",
"Breadtop",
"Broadway Crown",
"Mr. Wu Dumpling Bar",
"Gotcha Fresh Tea UTS",
"Nakano Darling",
"PappaRich UTS University",
"Planet Pizza Glebe",
"Malacca Straits on Broadway",
"Toastiesmith Darling Square",
"Red Lemon Thai",
"The Rendez Vous Crepe Broadway Sydney",
"Ultimo Kitchen",
"159 Home Kitchen",
"77 Dumpling King",
"Anjappar",
"Biang Biang noodles",
"Bun Me Broadway",
"Cafe Harris",
"Caysorn Thai",
"Din Tai Fung Broadway",
"Dodee Paidang Haymarket",
"Dumpling & Noodle House",
"Elements Bar and Grill Pyrmont",
"Happy Chef Noodle Restaurant",
"Harry's Café de Wheels - Ultimo",
"IIKO Mazesoba",
"It's Time For Thai",
"Kowloon Cafe Sydney",
"Kura Kura Japanese Dining",
"Lestari Resto",
"Little Sichuan Canton小川粤",
"Mamak Haymarket",
"Menya Chinatown",
"Merchants of Ultimo",
"Metro Pita Kebab",
"Ming Fu Restaurant",
"MISO Japanese Restaurant",
"Mr. Wong",
"Mumbai Express",
"Nando's Broadway S/C",
"Pizza M",
"Rebowl Chinese Restaurant",
"Saigon Pho",
"Sapa Modern Vietnamese Restaurant",
"Shiba's Kitchen",
"Sizzling King",
"Social Brew Cafe",
"Subway",
"Sushi Hon",
"Sushi Hub Sydney Central",
"Taste Legend",
"The Hub Burger Bar",
"The Pigeonhole Cafe",
"The Small Lemongrass",
"UniBros",
"Wattle Diner",
"Sushi Centre",
"Indian Leaf",
"Ba Shan",
"Bread & Circus",
"Donburo",
"Fourth Village Providore",
"Luxe Waterloo",
"Harshita’s Kitchen",
"CafeOZ",
"Thailicious",
"East Phoenix",
"Plus Two Coffee",
"Two Peck Crispy Chicken",
"Kepos Street Kitchen",
"149小馆",
"3 Fish and Chips",
"AllSpice Thai Kitchen",
"Ambience Cafe",
"ANGELO PASCUCCI",
"Angry BBQ 怒烤烤串",
"Arancini",
"Bloc145",
"Chicken Bite Waterloo",
"China Bowl",
"Chongqing Street Noodles",
"Cuppa Flower",
"D-Eight Fried Chicken & Burgers 点吧-炸鸡汉堡",
"Deli on Waterloo",
"Double",
"Doytao Thai",
"Five Star Thai Narrabeen",
"Fun House",
"Gibbons Street Cafe Redfern",
"Haak Eatery",
"Hungry Chefs Cafe",
"Johnny Gio's Waterloo",
"Just Fry",
"Kukthai",
"Malatown",
"Manoosh Pizzeria - Waterloo",
"Mecca Coffee",
"Milk Crate Waterloo",
"Mr Sun's Fried Bun",
"Nando's Alexandria",
"Nem Kitchen",
"Origano Woodfire Pizza",
"Pino Espresso Bar",
"Pizza Deli",
"Pizza Hut Waterloo",
"Pyrmont Kebabs",
"Salsabil",
"Samir's Indian Kitchen",
"Skina Cafe Bar",
"Sushi Aoki",
"Take Sushi & Japanese Cuisine",
"Taste of Spicy",
"Terry's Grill @ George Hotel",
"The Crystal Restaurant n Bar",
"Treetop Cafe",
"Urban Thai",
"Vasco",
"Wah Wah Lounge",
"Wholly Schnit",
"Yen's Vietnamese Restaurant",
"Yes Thai",
"Zoo Family",
"六福鱼水饺 Luckfood Fish Dumplings",
"John Montagu",
"China Doll",
"Slashed Burger",
"Contact Bar & Kitchen",
"Espetus Churrascaria",
"Foodoomooloo Turkish Street Food",
"Harry's Coffee & Gelato",
"Woolloomooloo Fish & Chips",
"P'Nut Street Noodles Zetland",
"Cafe Portman",
"Indian Rasoi Zetland",
"A Taste of Taiwan Zetland",
"Brazilian Flame Meats And Barbeque",
"Camy's Chargrill Chicken",
"Copacabana Bar",
"Griddle King 小零煎餅",
"Kickin'Inn Zetland",
"Lucio Pizzeria",
"Miso Japanese Teishoku Restaurant",
"Ribs & Burgers Zetland",
"Rose Valley Canteen",
"Saigon Xpress Roll",
"Sushi Square",
"Taco Bell Green Square",
"Taisho Wagyu Beef BBQ",
"Victoria Park Cafe",]



account = pcli.accounts.list_all(q={"name" :{"$in" : businesNames}})



for i in account:
    print(i.name ,"*-*" ,i._id)