names = ["The Bavarian Green Hills",
"Schnitz Wollongong",
"Schnitz Wagga Wagga",
"Grill'd Wollongong",
"Grill'd Tweed City",
"Grill'd",
"Kinn Thai Restaurant",
"Mylan",
"Beast - Good Food Eatery",
"Top Choice",
"Chicken V Wollongong",
"Outback Steakhouse Wollongong",
"TGI Fridays",
"Sandwich Chefs",
"Pemberton Pantry",
"Wok It Up",
"Whitney’s Restaurant & Bar",
"Big Fella's Burgers",
"Kasalong Thai Restaurant Richmond",
"Classic Noodle House",
"Burger Urge (Forster)",
"Pizza Hut East Maitland",
"Pizza Hut Orange Dine In",
"Pizza Hut Windsor Dine In",
"Pizza Hut",
"Pizza Hut Bathurst",
"Pizza Hut Nowra",
"Pizza Hut Griffith",
"Guzman y Gomez - Wollongong",
"Guzman y Gomez - Coffs Harbour",
"Lone Star Rib House & Brews East Maitland",
"Burger Urge (Tamworth)",
"Burger Urge (Armidale)",
"Uneke Lounge",
"8Things Katoomba",
"Addimi",
"An Chut Chut",
"Apracurryhouse",
"At Roi Thai Restaurant Cessnock",
"Aura Thai",
"Baan Sabai Jai Thai Restaurant",
"Bangalay Dining",
"Baskk Italian",
"Bay Street Takeaway",
"Beach Bums Cafe",
"Beach Burrito Co.",
"Beach Street Seafoods",
"BELEAF TABLE Japanese Restaurant",
"Pinto Thai Restaurant Coolangatta",
"Benny's Restaurant and Bar",
"Centro CBD",
"Zahara Turkish Restaurant",
"Asty's @Shelly Beach",
"Lighthouse Beach Takeaway",
"Black Box Pizza and Icecream",
"Blue Whale Asian Eatery",
"Bonetti's Takeaway & Delivery",
"Village Pantry",
"Thorne Street Cafe",
"Sonny’s Bakery",
"Alchemy",
"Black Tambourine",
"Leaves & Fishes",
"Dorys Takeaway",
"RUSH roasting co BOWRAL",
"Vudu Food Bar",
"The Hungry Monkey",
"Brooklyn’s Burger Bar Espresso Thrumster",
"Bua Thong",
"Buk Choy Thai Lao Eatery",
"BurgerBulls",
"Burger Chef",
"Burger Chef",
"Burgie's Burger Bar & Cafe",
"By the Sea take away",
"Cafe 5911",
"Cafe Dalchini",
"Café Veloce",
"Carnation Thai Restaurant",
"Cascada Restaurant",
"Cattlefish",
"Cessnock Curry & Kebabs",
"Charm 9",
"Chork Dee Thai Restaurant",
"Crust Pizza Port Macquarie",
"Coolabah Tree Cafè",
"Dark Arts Cafe & Bar",
"SoCo Kitchen & Bar Wollongong",
"Moominn",
"Litani's Mediterranean Restaurant",
"Roppongi Japanese Restaurant",
"Illnara Korean Restaurant",
"Lee and Me",
"@Thai Gong Restaurant",
"Lupa Woodfired Pizza",
"Yachties' Cafe",
"Soul Origin Wollongong Central",
"Opus Coffee Brewers",
"Kürtősh - Wollongong",
"Romano's pizzeria",
"Bohemian Cafe & Catering",
"Wonder Sushi Windsor",
"Café Leura - Modern Australian Restaurant",
"Tanoshi",
"Dogwood, BX - Restaurant Bathurst",
"Zambrero Coffs Harbour",
"Indian Cottage",
"Ottoman Kebabs",
"McDonald's",
"Coffs Harbour Golden Hot Bread",
"Amigos Mexican Restaurant",
"The Bavarian Wollongong",
"Jimmy's Burger Bar",
"Zambrero Wollongong",
"Viet'z eatery",
"BackStreet Kitchen",
"Sneaky Burger Wollongong",
"Co May Vietnamese Restaurant",
"Bangkok Balcony",
"Little Vietnam Restaurant",
"Saigon Senses Wollongong",
"Tsuki Dining",
"Hanoi Vietnamese Takeaway Food",
"Lettuce B. Frank",
"Miss Lee's",
"Food World Cafe",
"Bourke Street Burgers",
"TaChun Chinese Restaurant",
"Northgong Thai Restaurant",
"McDonald's Wollongong",
"Koon Hong",
"Indian Home Diner Wollongong",
"Gourmet Pizza World Wollongong",
"The Asian Takeaway",
"The Coffee Club Café - Wollongong",
"Student Biryani Wollongong",
"Al Aseel Restaurant Fairy Meadow",
"Winnie's",
"Aloi...D Thai take away",
"Lavenders Cafe",
"Mustafa's Kebab House & Cafe",
"Fifi's Take Away",
"Hungry Jack's Burgers Maitland",
"BungaRaya@Easts",
"Lorong Malaysia",
"Hong Kong Chef",
"Donut King",
"Wok n Roll",
"Sushi Hub Green Hills",
"Sunshine Kebabs",
"Burger Urge (Green Hills)",
"High Street Takeaway",
"Noodle Bar",
"Roll'd Greenhills",
"Mad Mex Fresh Mexican",
"Sway Thai Fusion & Bar",
"Get Hooked Seafoods",
"Mofos Tweed Heads",
"Outlaw Pizza",
"Sushi Hub Tweed City",
"PKG Seafood Wholesale",
"Vinnys Pizza Pasta & Ribs",
"Red Rooster Tweed Heads",
"Kirra Shop at Kirra Shores",
"Hungry Jack's Burgers South Tweed",
"Montezuma's Mexican Restaurant & Bar - Coolangatta, QLD",
"Govindas Coolangatta",
"Lam Kitchen Bar",
"Feng Shui Chinese Restaurant",
"Sushi Train Coolangatta",
"Murasaki Teppanyaki Broadbeach",
"The Grill",
"Blue Water Bar & Restaurant",
"Hog's Breath Cafe Port Macquarie",
"Zambrero Port Macquarie",
"Maharaja Tandoori - Indian Restaurant",
"Off The Hook Fish & Chips",
"Calvins Chicken Shop & Take-away",
"Wok Mania",
"Subway",
"Subway",
"Hungry Jack's Burgers Port Macquarie",
"Milkbar Townbeach",
"Donut King Settlement City",
"Churro Fondue",
"Zambrero",
"Okami Japanese Restaurant",
"Kung Fu Dumplings",
"Duke of Kent Hotel",
"Original Flame Grilled Chicken",
"Noodle Paradise",
"Hungry Jack's Burgers Wagga Wagga",
"Golden Bowl Chinese",
"Kungfu Dumplings",
"New Oceanic Take Away",
"Sushi Hub Wagga Wagga",
"The Coffee Club Café",
"Baylis Grind Cafe",
"Subway",
"10 Best St.",
"Wendy's",
"Gelatissimo Wagga Wagga",
"Din Dins",
"South Cali Cantina",
"Yuu Sushi",
"Zambrero",
"Downtown Pizzeria",
"Indian Tandoori Restaurant",
"Urban Graze",
"Green Zebra",
"Mad Mex Fresh Mexican",
"Carv'n It Up",
"Roma Restaurant and Pizzeria",
"Noodle Place",
"Timber",
"Authentic taste of India",
"Subway",
"Sweethearts Pizza",
"Get Tossed Salad Bar",
"Hungry Jack's Burgers Albury",
"Beechworth Bakery Albury",
"Subway",
"Turquoise Turkish Restaurant",
"Villa Olivo",
"Punjabi Hut Indian Restaurant",
"Slow Noodle Fast",
"KC'S Takeaway",
"Hungry Jack's Burgers Queanbeyan",
"Nerson's",
"Subway",
"Gilmore Cafe",
"Bean Central",
"Spice Bar Indian Restaurant & Liquor Store",
"Zambrero Orange",
"Shymigriel Asian and Australian Cuisine",
"Trang's Kitchen",
"Yoshi Sushi",
"The BoW Project",
"New Golden Bowl Chinese Restaurant",
"Taco Bell Orange",
"Pho Orange",
"Indian Delight- Take away/Resturant",
"Choox Burgers, Wings & Ribs Pop Up Store",
"Country Kebabs and Pizzas",
"Hungry Jack's Burgers Orange",
"McDonald's",
"The Coffee Club",
"Tamworth Vietnamese Restaurant",
"Zambrero",
"Cafe Vivaldi",
"Tam Tam Sushi",
"Taco Bell Tamworth",
"Margarita's Pizzeria",
"Hungry Jack's Burgers Tamworth",
"Subway",
"Spicy Indian Treat",
"Flaming Fusion",
"CRAZIES cafe",
"Food Coma Pizzeria",
"89 Thai Windsor",
"Patiala House Indian Restaurant",
"Orchid 22 Chinese restaurant",
"Tandoori Village",
"Windsor Thai",
"Cobb & Co",
"Classic Indian Curry Hut",
"Noodle Paradise",
"Pizza Castle",
"Chutney Cafe",
"The River Orchid Chinese Restaurant",
"Da-Wish Food Station",
"Daddy's Burgers 'n Wings",
"Subway",
"4 Beans Cafe",
"Nargis Foods Indian & Kebab",
"Riverview Carvery & Burger Co",
"The Postbox Takeaway",
"Jamaica Blue",
"Oporto Claredon Drive Thru",
"Westlake Chinese Restaurant",
"Zambrero",
"Okami Japanese Restaurant",
"Down The Lane",
"Jimmy's Kitchen",
"Royal India Restobar",
"The Monkey Bar",
"Four Seas Chinese Restaurant",
"Mad Mex Fresh Mexican",
"Pizza Monster",
"Mr Wang Kitchen",
"Tempt Sweet & Savoury",
"Relish Cafe & Catering",
"Zenab Kebabs",
"Burger Urge (Dubbo)",
"Fantastic noodle bar",
"The Auctioneer Cafe and Bar",
"Peter & Angela's Gourmet take/away",
"Wok N Roll",
"Sweet Caramel",
"The Jewel of Bathurst",
"Wishbone Chicken",
"Hungry Jack's Burgers Bathurst",
"O MY GRILL",
"Hometown Cafe Bathurst",
"KC Seafood",
"Indian Flavour Authentic Indian Cuisine",
"Hog's Breath Cafe Coffs Harbour",
"Maria's Italian Restaurant",
"Dumpling Bar",
"Hungry Jack's Burgers Coffs Harbour",
"Raw Bar By @chocdaisy",
"Fire Pizza Kebab",
"Rozana Charcoal Chicken",
"Thai Satay Hut",
"Kohlis Indian Restaurant Nowra",
"Thai Riverside Restaurant",
"Zambrero Nowra",
"Sneaky Burger Nowra",
"Elephant Thai Cafè And Restaurant",
"Leong's Chinese Restaurant",
"Oporto Nowra Stockland",
"Oporto South Nowra",
"Hungry Jack's Burgers South Nowra",
"Subway",
"Nowra Kebabs",
"Curry cottage Indian cuisine",
"Goulburn Charcoal Chicken",
"Zambrero",
"Forked",
"G&A Quality Chicken",
"Ogys Kebab Express",
"The Coffee Club - Goulburn Square",
"Hungry Jack's Burgers Goulburn",
"Subway",
"An Indian Affair",
"PJ Thai",
"The Minnie Barn",
"R&H Curry House",
"McDonald's",
"Subway",
"Hungry Jack's Burgers Armidale",
"EatstreetPH Armidale",
"Zambrero",
"Casablanca Cafe",
"Shiva's Food Court",
"Ali Baba Kebab Palace",
"Subway",
"Caffe Rosso Bowral",
"JB KITCHEN (Modern Australian Cafe Style Food)",
"wt1331 Cafe & Bakery",
"Earth 'n' Sea Pizza",
"Fins Restaurant and Bar",
"Overlander Indian Restaurant",
"Tastify Richmond",
"Tastify Bligh Park",
"Kitchen On The Bay",
"Eat inn",
"El Chapos",
"El Guapo Cantina Bathurst",
"CHEFS OWN BY ROB",
"Yummy Kingdom",
"Anam Restaurant",
"Fiasco Ristorante Bar",
"FLAME WOODFIRE PIZZERIA",
"Flippin Pizza",
"Kikiees Restaurant",
"Levant Restaurant",
"Fat Boy Grill & Pide",
"il Pozzo Cafe",
"Mellow Bistro",
"Lee's Kitchen",
"Pan-Asia",
"Tweed Indian Hut",
"Ji’s Fish & Chips",
"Pan Asia Rice and Noodles",
"Margaret & Sons Pasta Place",
"Ray Rays Diner",
"Golden Recipes",
"Belair Pizza & Pasta",
"COUNTRY CURRY & KEBAB",
"Tasty Tibetan Treats",
"Guru's Cafeteria and Pizzeria",
"Mad Chef Indian & Thai Restaurant",
"The Corner Shack",
"The Second Home Cafe - Richmond",
"The Grill On George",
"Jai's Pizza & Pasta Richmond",
"Daawat Indian Restaurant",
"The Lions Pride Cafe & Restaurant",
"The Vietnamese House",
"Golden Dragon Chinese Restaurant",
"The Captains Catch",
"Burgers on William",
"Tuscany Wood Fired Restaurant",
"Forster Noodle Bar",
"Ban Thai restaurant",
"Mandy's Restaurant",
"Rendezvous Eat In and Take Away",
"Neville's Store",
"Grab 'N' Gobble Take Away (Armidale )",
"East Armidale Store",
"Genki Sushi &Genki Tea Griffith",
"Mango duck",
"Family Curry Hub Indian Restaurant",
"Thai at 27",
"Deepka Indian Restaurant",
"Straw Pavilion",
"The Table - Thai and Filipino Cuisine",
"Happi Chicken",
"Kurri Curry and Kebabs",
"The Bay Leaf Authentic Indian Restaurant",
"Food'n A Flash",
"Fortune Kitchen",
"Golden Terrace Chinese Restaurant",
"Goulburn Seafood Restaurant",
"Gourmet Pizza Cessnock",
"Gracie Burger",
"Grill'd Coolangatta",
"Group Therapy Coffee",
"Ha Noi Corner",
"Harbour View Thai Kiama",
"The Heights Sports Club Bistro",
"Northbeach Pavilion Pizza, Pasta, Bar & Kiosk",
"Moreish Cafe",
"Supply Speciality Coffee and Bar",
"The Silly Goat",
"Valley Cafe",
"Diggies Kiama",
"Hayden's Pies",
"Hidden Gem @ Marina",
"HiPoke",
"Samaras Restaurant",
"2 Smoking Barrels Barbecue Joint & Food truck",
"Belair pizza",
"Village Bakehouse Orange",
"Village Bakehouse",
"B Town BBQ",
"The Oxford Bathurst",
"Lime Mexican Sawtell",
"El Corazon Cocina de Mexico",
"Hungry Jack's Burgers Broken Hill",
"Hunter Gourmet Pizza Greenhills",
"Hydration.Maitland",
"Il Corso Cafe Griffith",
"Indian Chimney Restaurant",
"Indian Rasoi",
"Jay's Food Emporium Coolangatta",
"Jords Sandwich Bar",
"KFC Coffs Harbour South",
"KFC Coffs Harbour Plaza",
"KFC Wollongong Central",
"KFC East Maitland",
"KFC Tweed City Food Court",
"KFC Tweed Heads",
"KFC Port Macquarie",
"KFC Port Macquarie II",
"KFC North Wagga",
"KFC Sturt Mall Food Court",
"KFC Wagga Homebase",
"KFC Albury",
"KFC West End Plaza Food Court",
"KFC Queanbeyan",
"KFC Orange",
"KFC Tamworth",
"KFC Tamworth South",
"KFC Richmond South",
"KFC Dubbo - Drive Through only",
"KFC Bathurst",
"KFC Nowra",
"KFC Forster",
"KFC Goulburn",
"KFC Goulburn South",
"KFC Armidale",
"KFC Griffith",
"KFC Grafton",
"KFC Grafton Food Court",
"KFC Broken Hill",
"KFC Cessnock",
"KFC Ballina",
"KFC Ballina Travel Centre",
"KFC Taree",
"KFC Taree Service Centre",
"KFC Raymond Terrace",
"KFC Singleton",
"KFC Kurri Kurri",
"KFC Ulladulla",
"KFC Batemans Bay",
"Kingsley's Chicken Queanbeyan",
"Kinn Thai Greenhills",
"Kneading Ruby",
"KT Bee's Kitchen",
"Lavish Coffee & Cuisine",
"Lex Thai Garden",
"Nile Street Cafe",
"Living Room Wollongong",
"Aunty Ed's Restaurant And Bar",
"LEAF in Nowra",
"Luna Bonita",
"Mandarin Palace",
"Maneeya Thai Restaurant",
"Mangotree Restaurant Wollongong",
"Mannu's Kitchen Indian Cuisine Maitland",
"Manor Thai Restaurant",
"Mary G's",
"McDonald's Coffs Harbour Service Centre",
"McDonald's",
"Mcdonalds",
"McDonald's",
"McDonald's Coolangatta II",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's Queanbeyan",
"McDonald's",
"McDonald's Tamworth",
"McDonald's Tamworth West",
"McDonald's Tamworth South",
"McDonald's Richmond",
"McDonald's Bligh Park",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's Griffith",
"McDonald's",
"McDonald's",
"McDonald's",
"McDonald's Ballina",
"McDonald's",
"McDonald's Glenthorne",
"McDonald's Raymond Terrace",
"McDonald's - Heatherbrae",
"McDonald's",
"McDonald's",
"McDonald’s",
"McDonald's",
"McDonald's",
"Kebabs @ Victoria",
"Memory Thai",
"Bubble Pop, The Boba Tea Shack",
"Red Rooster Park Beach Plaza",
"Muffin Break",
"Gloria Jean's Coffees Coffs Harbour",
"Da Orlando Pizzeria",
"Souva King",
"Ziggy's House of Nomms",
"Taste of Xi'an 西安风味",
"Crust Pizza Wollongong",
"Julio's Pizza",
"Ken's Kitchen",
"Crust Pizza Maitland",
"Wildflame Barbecue and Bar",
"Crafty Eats",
"Tre Viet Kitchen",
"Village Kebab & Curry",
"The Sea Shanty",
"Be Thai",
"Reyhana",
"Oriental Spoon Korean Restaurant",
"Suzu Japanese Dining",
"Wall of China",
"Town Green Buffet and Bar",
"Little Turkey",
"Chez Sushi",
"Pipeworks Cafe",
"Ports Sacred Pizza",
"Saltwater Takeaway",
"The Roundabout Restaurant",
"Hog's Breath Cafe Wagga Wagga",
"Nabiha's kitchen",
"Corea",
"Funky Mexican Cantina",
"Crust Pizza Wagga Wagga",
"Noodle King",
"Fitz Cafe",
"JD's Kebabs Chicken Pizza",
"M R . L A W R E N C E",
"Turvey Tops Chinese Takeaway & Delivery",
"Kooringal Chinese Restaurant",
"Hovell Bar & Grill Albury",
"Saludos",
"Zen X",
"Social Dining & Bar @ SS&A Albury",
"House of Ivy",
"Albury Chinese Restaurant",
"As Thick As Thieves",
"Pan-Lan Chinese Restaurant",
"The Chow Shop",
"The Coffee Club Café - Albury",
"South China Restaurant",
"That Nutrition Place Albury",
"AJ's Cafe Take Away",
"Crust Pizza Queanbeyan",
"Ali Baba",
"Hog's Breath Cafe Orange",
"Dum Dum Dumplings",
"The Mills",
"Wing Wah Chinese Restaurant",
"Loc Sing Restaurant",
"Venue Cafe Bar",
"Fresh Food Fast",
"Alis Kebab",
"Suli Sushi",
"Donut King Orange City Centre",
"Bad Burgers Fish n Chips",
"Riviera Bar & Grill",
"Zaya Sushi(eat in,take away&delivery)",
"Hog's Breath Cafe Tamworth",
"Central Chinese Restaurant",
"Seafood and Kebab Bar",
"hideaway bistro",
"The Coffee Club Café - Tamworth",
"JJ's Kebabs and Pizza",
"East Court Restaurant",
"Liva's Cafe & Restaurant",
"Dom's Pizza Pasta Windsor",
"Simon's Cafe",
"Sun Sing Chinese Restaurant",
"Stir Crazy",
"Windsor Palace Chinese",
"Soo's Chinese Restaurant",
"Acropolis Yeeros",
"Oregano King Plate",
"Sushi Chat",
"Ala Sultan",
"DaNiro's Pizzeria",
"Thai Buffalo",
"Donut King Richmond Marketplace",
"Ozzy Kebabs",
"Old Bank Restaurant & Bar",
"Nights' Grill",
"The Shire Bar & Grill",
"Happy Chinese Restaurant",
"Pastoral Hotel",
"Sushi Haru",
"Spartans Pizzas",
"Oporto",
"Ted's Take Away",
"Coffee & Tea Exchange",
"Rockabilly Cafe",
"Zambrero Bathurst",
"Vanilla Bean Cafe & Restaurant",
"Good Catch Cafe PTY Ltd.",
"Venue Cafe Bar",
"Ristretto Bathurst",
"Ispa Kebab",
"Panorama Mini Mart & Takeaway south bathurst",
"Creasian Restaurant",
"Bombay Brasserie",
"Pig and Khai",
"Thai Inthanon Kitchen",
"Mr Deng's Chinese Restaurant",
"Surf Club Restaurant & Bar",
"Ootoya Japanese Sushi Bar",
"Lalin Thai Kitchen",
"Attitude Burgers",
"Banana Coast Seafood",
"Yum Yum Noodle",
"Chopsticks Chinese",
"PhoenWong Restaurant",
"Gurus masters of Indian cuisine",
"Win's Thai Kitchen",
"Red Dragon",
"Istanbul Kebabs",
"Pacific Palace Chinese Restaurant",
"Swiss Chalet Cafe",
"Peking Palace Chinese Takeaway",
"JBN Cafe",
"Vietnam Journey",
"Bey Kebabs",
"Bombay Bistro - cafe , restaurant & bar",
"Silver Spoon Nowra",
"Postman's Tavern",
"Tokyo Sushi",
"Oporto - Vincentia",
"Royal Indian Cuisine",
"Jamaica Blue Forster",
"Cascades Restaurant",
"The Camellia Chinese Restaurant",
"Goulburn Chinese Restaurant",
"Golden Star Restaurant",
"Emperor Asian Restaurant",
"Lotus Chinese Restaurant",
"Southern Star Inn",
"Home98 Thai Restaurant",
"Ravi's Curry In A Hurry",
"NỘI",
"The ASTOR Bistro",
"Crust Pizza Goulburn",
"Goulburn Kebab",
"Greengrocer on Clifford",
"Chickenman Goulburn",
"Yellow Deli",
"Thai Square",
"Gasiinsamut Thai Fusion",
"Thai Square - Leura",
"hao sushi and grill",
"A&J Vietnamese Restaurant",
"코니 - KONI",
"Colombo Kottoo",
"Pearl Perch Takeaway",
"ISPA KEBABS",
"Indian Cottage",
"Stone's on Argent",
"Metro Petroleum",
"Chicken V",
"Zambrero Cessnock",
"Snitzerellas",
"Thai by Night",
"Mumbai Masala Indian Restaurant",
"Taco Bell Ballina",
"YUMMY KITCHEN TAREE",
"Jack & Co Taree Central",
"Toppers Pizza",
"WonderSushi",
"Janeks Cafe",
"Allumer Coffee & Eatery",
"JJ's Indian Restaurant Kiama",
"Nirand Thai Restaurant",
"Dragon Garden Chinese Restaurant",
"Addil Indian and Kebab Restaurant",
"Terrace diner and play",
"Terrace Central Takeaway & Seafood",
"Taj Indian Flavours Indian restaurant",
"Pearl Light Palace",
"Bellygood",
"Zambrero Singleton",
"Addil Indian & Kebab",
"Singleton Kebabs (Kebabs & Gozleme)",
"Horse and Jockey",
"Green Hills Chinese Takeaway",
"Domino's Pizza Gillieston Heights",
"Subway",
"Kohlis Waterfront Indian Restaurant",
"Messina Pizza and Pasta",
"Oporto Tamworth Drive Thru",
"Oporto",
"Moo Moos",
"Oporto Cessnock Drive Thru",
"Kimono",
"Momo's Coffees Burgers Curries",
"Monkey King Thai - Richmond",
"Mr Mozzarella Ballina",
"His Boy Elroy",
"Ground Kitchen",
"Cin Cin Pizza Cucina",
"Baked at Ancora",
"Giuseppe's Restaurant & Bar",
"Manyana Mexican Taqueria",

"Frankly My Dear Coffee",
"Giuseppe's Restaurant & Bar",
"BENT ON FOOD",
"RAW & WILD Market & Cafe",
"Muki Cafe",
"Namaste wagga wagga",
"Karabar Takeaway",
"Northside Pizza Coffs Harbour",
"Nosh",
"Wildginger Huskisson",
"Ocean Project Café Restaurant",
"Oishii Japanese and Thai Restaurant",
"Old Mate's Burgers",
"Greenstreat Albury",
"One Siam Thai restaurant",
"The Gong Cafe",
"Sudania Cafe and Restaurant",
"Beud",
]

query = pcli.accounts.list_all(q={"name" : {"$in" : names}})