import requests
import json
locations = [
"ADELAIDE CBD",
"ALTONA",
"ARMIDALE",
"BALWYN NORTH",
"BANGOR",
"BANKSTOWN",
"BAYSWATER",
"BENDIGO",
"BENTLEIGH",
"BLACKBURN",
"BLACKTOWN ROAD, BLACKTOWN",
"BORONIA",
"BRIGHTON-LE-SANDS",
"BRUNSWICK",
"BURKE ROAD, KEW",
"BURWOOD",
"CABRAMATTA",
"CAMPBELLFIELD",
"CAROLINE SPRINGS",
"CASULA",
"CENTRE ROAD, BENTLEIGH",
"CHATSWOOD",
"CRAIGIEBURN ROAD, CRAIGIEBURN",
"CROYDON",
"DANDENONG",
"DARWIN",
"DONCASTER",
"DOREEN",
"DUNDAS",
"EAGLE FARM",
"EASTWOOD",
"EPPING",
"FOOTSCRAY",
"FRANKSTON",
"GLEN HUNTLY",
"GLEN WAVERLEY",
"GREENACRE",
"GREENFIELD PARK",
"GREENSBOROUGH",
"HAMPTON",
"HOPPERS CROSSING",
"KEILOR",
"KINGSTON",
"KOGARAH",
"LALOR",
"LILYDALE",
"LIVERPOOL ROAD, ASHFIELD",
"MACKAY",
"MELBOURNE CBD",
"MELTON",
"MENTONE",
"MILL PARK",
"MITCHAM",
"MITCHELL",
"MOOROOLBARK",
"MOUNT WAVERLEY",
"NARRE WARREN SOUTH",
"NEWTOWN",
"NORTH SYDNEY",
"OAKLEIGH",
"PADSTOW",
"PARRAMATTA ROAD",
"PHILLIP",
"PRESTONS",
"RAILWAY PARADE, EASTWOOD",
"RINGWOOD",
"ROSANNA",
"SCORESBY",
"SOUTH MORANG",
"SOUTH YARRA",
"SPRINGVALE",
"STEPHENSONS ROAD, MOUNT WAVERLEY",
"STEPNEY",
"ST MARYS",
"SUNBURY",
"SURRY HILLS",
"SUTHERLAND",
"SYDNEY: 83 MOUNT STREET",
"TOWNSVILLE",
"UNION RD, ASCOT VALE",
"WANTIRNA SOUTH",
"WARRINGA CRESCENT, HOPPERS CROSSING",
"WENTWORTHVILLE",
"WEST PYMBLE",
"WETHERILL PARK",
"WHITEHORSE ROAD, BALWYN",
"TOOWOOMBA",
"ULTIMO",
]

clMapping = {"ADELAIDE CBD": "Epic Hotdog",
"ADELAIDE CBD": "Ben's Burgers",
"ADELAIDE CBD": "Absurd Bird",
"ADELAIDE CBD": "Epic Chicken",
"ADELAIDE CBD": "Big George's Burgers",
"ADELAIDE CBD": "World of Wings",
"ADELAIDE CBD": "Wing World",
"ADELAIDE CBD": "Dog n Bun",
"ALTONA": "On The Wing",
"ALTONA": "Epic Hotdog",
"ALTONA": "World of Wings",
"ALTONA": "Wing World",
"ALTONA": "Dog n Bun",
"ARMIDALE": "World of Wings",
"ARMIDALE": "Wing World",
"BALWYN NORTH": "Epic Chicken",
"BALWYN NORTH": "Wing World",
"BALWYN NORTH": "Absurd Bird",
"BALWYN NORTH": "World of Wings",
"BANGOR": "On The Wing",
"BANKSTOWN": "Absurd Bird",
"BANKSTOWN": "On The Wing",
"BANKSTOWN": "Wing World",
"BANKSTOWN": "World of Wings",
"BANKSTOWN": "Epic Chicken",
"BAYSWATER": "Legit Burgers",
"BAYSWATER": "OTT Burgers",
"BAYSWATER": "Ben's Burgers",
"BAYSWATER": "World of Wings",
"BAYSWATER": "Wing World",
"BENDIGO": "World of Wings",
"BENDIGO": "Wing World",
"BENDIGO": "On The Wing",
"BENTLEIGH": "OTT Burgers",
"BENTLEIGH": "Ben's Burgers",
"BENTLEIGH": "Big George's Burgers",
"BENTLEIGH": "Legit Burgers",
"BLACKBURN": "On The Wing",
"BLACKBURN": "Wing World",
"BLACKBURN": "World of Wings",
"BLACKTOWN ROAD, BLACKTOWN": "On The Wing",
"BLACKTOWN ROAD, BLACKTOWN": "Ben's Burgers",
"BLACKTOWN ROAD, BLACKTOWN": "Big George's Burgers",
"BORONIA": "Dragon Ear",
"BORONIA": "Wing World",
"BORONIA": "On The Wing",
"BORONIA": "Big George's Burgers",
"BORONIA": "Ben's Burgers",
"BORONIA": "Epic Chicken",
"BORONIA": "Absurd Bird",
"BORONIA": "World of Wings",
"BORONIA": "Ungki's",
"BRIGHTON-LE-SANDS": "On The Wing",
"BRUNSWICK": "Wing World",
"BRUNSWICK": "Dragon Ear",
"BRUNSWICK": "Ungki's",
"BRUNSWICK": "On The Wing",
"BRUNSWICK": "World of Wings",
"BURKE ROAD, KEW": "Ben's Burgers",
"BURKE ROAD, KEW": "Dog n Bun",
"BURKE ROAD, KEW": "Epic Hotdog",
"BURKE ROAD, KEW": "Big George's Burgers",
"BURWOOD": "On The Wing",
"BURWOOD": "Wing World",
"BURWOOD": "World of Wings",
"CABRAMATTA": "Wing World",
"CABRAMATTA": "Absurd Bird",
"CABRAMATTA": "Epic Chicken",
"CABRAMATTA": "World of Wings",
"CAMPBELLFIELD": "On The Wing",
"CAMPBELLFIELD": "Wing World",
"CAMPBELLFIELD": "World of Wings",
"CAROLINE SPRINGS": "Dog n Bun",
"CAROLINE SPRINGS": "Epic Hotdog",
"CASULA": "Wing World",
"CASULA": "World of Wings",
"CASULA": "Ungki's",
"CASULA": "Dragon Ear",
"CASULA": "On The Wing",
"CENTRE ROAD, BENTLEIGH": "Wing World",
"CENTRE ROAD, BENTLEIGH": "World of Wings",
"CENTRE ROAD, BENTLEIGH": "On The Wing",
"CENTRE ROAD, BENTLEIGH": "Absurd Bird",
"CENTRE ROAD, BENTLEIGH": "Epic Chicken",
"CENTRE ROAD, BENTLEIGH": "Ben's Burgers",
"CHATSWOOD": "Epic Hotdog",
"CHATSWOOD": "OTT Burgers",
"CHATSWOOD": "Epic Chicken",
"CHATSWOOD": "Legit Burgers",
"CHATSWOOD": "Ben's Burgers",
"CHATSWOOD": "Dog n Bun",
"CHATSWOOD": "Absurd Bird",
"CHATSWOOD": "On The Wing",
"CHATSWOOD": "Big George's Burgers",
"CRAIGIEBURN ROAD, CRAIGIEBURN": "Wing World",
"CRAIGIEBURN ROAD, CRAIGIEBURN": "World of Wings",
"CROYDON": "Dragon Ear",
"CROYDON": "World of Wings",
"CROYDON": "Wing World",
"CROYDON": "Ungki's",
"CROYDON": "Absurd Bird",
"CROYDON": "Epic Chicken",
"CROYDON": "Ben's Burgers",
"CROYDON": "Big George's Burgers",
"CROYDON": "On The Wing",
"DANDENONG": "Epic Chicken",
"DANDENONG": "On The Wing",
"DANDENONG": "Big George's Burgers",
"DANDENONG": "Ben's Burgers",
"DANDENONG": "World of Wings",
"DANDENONG": "Wing World",
"DANDENONG": "Ungki's",
"DANDENONG": "Dragon Ear",
"DANDENONG": "Absurd Bird",
"DARWIN": "Epic Hotdog",
"DARWIN": "Epic Chicken",
"DARWIN": "Absurd Bird",
"DARWIN": "OTT Burgers",
"DARWIN": "Dog n Bun",
"DARWIN": "World of Wings",
"DARWIN": "Wing World",
"DARWIN": "Legit Burgers",
"DONCASTER": "Big George's Burgers",
"DONCASTER": "Legit Burgers",
"DONCASTER": "OTT Burgers",
"DOREEN": "Wing World",
"DOREEN": "World of Wings",
"DUNDAS": "OTT Burgers",
"DUNDAS": "Legit Burgers",
"EAGLE FARM": "World of Wings",
"EAGLE FARM": "Wing World",
"EASTWOOD": "Wing World",
"EASTWOOD": "World of Wings",
"EPPING": "Wing World",
"EPPING": "On The Wing",
"EPPING": "World of Wings",
"FOOTSCRAY": "Wing World",
"FOOTSCRAY": "World of Wings",
"FOOTSCRAY": "Epic Chicken",
"FOOTSCRAY": "Absurd Bird",
"FRANKSTON": "On The Wing",
"FRANKSTON": "World of Wings",
"FRANKSTON": "Wing World",
"GLEN HUNTLY": "World of Wings",
"GLEN HUNTLY": "Wing World",
"GLEN WAVERLEY": "Ben's Burgers",
"GLEN WAVERLEY": "On The Wing",
"GLEN WAVERLEY": "OTT Burgers",
"GLEN WAVERLEY": "Legit Burgers",
"GLEN WAVERLEY": "Absurd Bird",
"GLEN WAVERLEY": "Epic Chicken",
"GLEN WAVERLEY": "World of Wings",
"GLEN WAVERLEY": "Wing World",
"GLEN WAVERLEY": "Big George's Burgers",
"GREENACRE": "Epic Chicken",
"GREENACRE": "Absurd Bird",
"GREENACRE": "Wing World",
"GREENACRE": "World of Wings",
"GREENFIELD PARK": "On The Wing",
"GREENSBOROUGH": "Wing World",
"GREENSBOROUGH": "World of Wings",
"HAMPTON": "World of Wings",
"HAMPTON": "Wing World",
"HOPPERS CROSSING": "Dog n Bun",
"HOPPERS CROSSING": "Absurd Bird",
"HOPPERS CROSSING": "Epic Chicken",
"HOPPERS CROSSING": "World of Wings",
"HOPPERS CROSSING": "Wing World",
"HOPPERS CROSSING": "Epic Hotdog",
"KEILOR": "Wing World",
"KEILOR": "World of Wings",
"KINGSTON": "Ben's Burgers",
"KINGSTON": "OTT Burgers",
"KINGSTON": "Big George's Burgers",
"KINGSTON": "Legit Burgers",
"KOGARAH": "World of Wings",
"KOGARAH": "Wing World",
"LALOR": "Epic Chicken",
"LALOR": "Absurd Bird",
"LALOR": "Wing World",
"LALOR": "World of Wings",
"LILYDALE": "Wing World",
"LILYDALE": "Ungki's",
"LILYDALE": "Dragon Ear",
"LILYDALE": "World of Wings",
"LIVERPOOL ROAD, ASHFIELD": "Epic Chicken",
"LIVERPOOL ROAD, ASHFIELD": "Wing World",
"LIVERPOOL ROAD, ASHFIELD": "On The Wing",
"LIVERPOOL ROAD, ASHFIELD": "Absurd Bird",
"LIVERPOOL ROAD, ASHFIELD": "World of Wings",
"MACKAY": "OTT Burgers",
"MACKAY": "Ben's Burgers",
"MACKAY": "Dog n Bun",
"MACKAY": "Big George's Burgers",
"MACKAY": "Epic Hotdog",
"MACKAY": "World of Wings",
"MACKAY": "Epic Chicken",
"MACKAY": "Absurd Bird",
"MACKAY": "Legit Burgers",
"MACKAY": "Wing World",
"MELBOURNE CBD": "Dog n Bun",
"MELBOURNE CBD": "World of Wings",
"MELBOURNE CBD": "Wing World",
"MELBOURNE CBD": "Epic Hotdog",
"MELBOURNE CBD": "Legit Burgers",
"MELBOURNE CBD": "OTT Burgers",
"MELTON": "Dog n Bun",
"MELTON": "World of Wings",
"MELTON": "Wing World",
"MELTON": "Absurd Bird",
"MELTON": "Epic Chicken",
"MELTON": "Epic Hotdog",
"MELTON": "On The Wing",
"MENTONE": "On The Wing",
"MENTONE": "Wing World",
"MENTONE": "World of Wings",
"MILL PARK": "Wing World",
"MILL PARK": "World of Wings",
"MITCHAM": "Epic Hotdog",
"MITCHAM": "Big George's Burgers",
"MITCHAM": "Ben's Burgers",
"MITCHAM": "Dog n Bun",
"MITCHELL": "World of Wings",
"MITCHELL": "Epic Chicken",
"MITCHELL": "On The Wing",
"MITCHELL": "Wing World",
"MITCHELL": "Absurd Bird",
"MOOROOLBARK": "Wing World",
"MOOROOLBARK": "World of Wings",
"MOUNT WAVERLEY": "World of Wings",
"MOUNT WAVERLEY": "Wing World",
"NARRE WARREN SOUTH": "Ben's Burgers",
"NARRE WARREN SOUTH": "Big George's Burgers",
"NARRE WARREN SOUTH": "Wing World",
"NARRE WARREN SOUTH": "World of Wings",
"NEWTOWN": "Wing World",
"NEWTOWN": "World of Wings",
"NORTH SYDNEY": "On The Wing",
"NORTH SYDNEY": "Wing World",
"NORTH SYDNEY": "Dog n Bun",
"NORTH SYDNEY": "Epic Hotdog",
"NORTH SYDNEY": "Ungki's",
"NORTH SYDNEY": "Dragon Ear",
"NORTH SYDNEY": "Ben's Burgers",
"NORTH SYDNEY": "Big George's Burgers",
"NORTH SYDNEY": "Absurd Bird",
"NORTH SYDNEY": "Epic Chicken",
"NORTH SYDNEY": "Legit Burgers",
"NORTH SYDNEY": "OTT Burgers",
"NORTH SYDNEY": "World of Wings",
"OAKLEIGH": "Wing World",
"OAKLEIGH": "World of Wings",
"PADSTOW": "Wing World",
"PADSTOW": "On The Wing",
"PADSTOW": "World of Wings",
"PARRAMATTA ROAD": "Dog n Bun",
"PARRAMATTA ROAD": "Epic Hotdog",
"PHILLIP": "Wing World",
"PHILLIP": "World of Wings",
"PHILLIP": "Absurd Bird",
"PHILLIP": "Epic Chicken",
"PHILLIP": "Ungki's",
"PHILLIP": "Dragon Ear",
"PHILLIP": "On The Wing",
"PRESTONS": "World of Wings",
"PRESTONS": "Wing World",
"PRESTONS": "On The Wing",
"RAILWAY PARADE, EASTWOOD": "Dragon Ear",
"RAILWAY PARADE, EASTWOOD": "On The Wing",
"RAILWAY PARADE, EASTWOOD": "Ungki's",
"RINGWOOD": "On The Wing",
"ROSANNA": "World of Wings",
"ROSANNA": "Wing World",
"SCORESBY": "Big George's Burgers",
"SCORESBY": "Ben's Burgers",
"SCORESBY": "On The Wing",
"SOUTH MORANG": "Wing World",
"SOUTH MORANG": "On The Wing",
"SOUTH MORANG": "World of Wings",
"SOUTH YARRA": "World of Wings",
"SOUTH YARRA": "Ben's Burgers",
"SOUTH YARRA": "Big George's Burgers",
"SOUTH YARRA": "Wing World",
"SOUTH YARRA": "Dog n Bun",
"SOUTH YARRA": "Epic Hotdog",
"SPRINGVALE": "World of Wings",
"SPRINGVALE": "Wing World",
"SPRINGVALE": "On The Wing",
"STEPHENSONS ROAD, MOUNT WAVERLEY": "On The Wing",
"STEPNEY": "World of Wings",
"STEPNEY": "Wing World",
"STEPNEY": "On The Wing",
"ST MARYS": "On The Wing",
"ST MARYS": "Big George's Burgers",
"ST MARYS": "Ben's Burgers",
"SUNBURY": "Wing World",
"SUNBURY": "Absurd Bird",
"SUNBURY": "Epic Chicken",
"SUNBURY": "World of Wings",
"SUNBURY": "Dog n Bun",
"SUNBURY": "Epic Hotdog",
"SUNBURY": "On The Wing",
"SURRY HILLS": "Wing World",
"SURRY HILLS": "Ben's Burgers",
"SURRY HILLS": "Big George's Burgers",
"SURRY HILLS": "World of Wings",
"SURRY HILLS": "Epic Chicken",
"SURRY HILLS": "Absurd Bird",
"SUTHERLAND": "World of Wings",
"SUTHERLAND": "Wing World",
"SUTHERLAND": "Absurd Bird",
"SUTHERLAND": "Epic Chicken",
"SYDNEY: 83 MOUNT STREET": "Absurd Bird",
"SYDNEY: 83 MOUNT STREET": "OTT Burgers",
"SYDNEY: 83 MOUNT STREET": "Big George's Burgers",
"SYDNEY: 83 MOUNT STREET": "Ben's Burgers",
"SYDNEY: 83 MOUNT STREET": "Dragon Ear",
"SYDNEY: 83 MOUNT STREET": "Ungki's",
"SYDNEY: 83 MOUNT STREET": "Epic Hotdog",
"SYDNEY: 83 MOUNT STREET": "Wing World",
"SYDNEY: 83 MOUNT STREET": "Dog n Bun",
"SYDNEY: 83 MOUNT STREET": "Legit Burgers",
"SYDNEY: 83 MOUNT STREET": "On The Wing",
"SYDNEY: 83 MOUNT STREET": "Epic Chicken",
"SYDNEY: 83 MOUNT STREET": "World of Wings",
"TOWNSVILLE": "Ben's Burgers",
"TOWNSVILLE": "Absurd Bird",
"TOWNSVILLE": "Epic Chicken",
"TOWNSVILLE": "Legit Burgers",
"TOWNSVILLE": "OTT Burgers",
"TOWNSVILLE": "World of Wings",
"TOWNSVILLE": "Wing World",
"TOWNSVILLE": "Dog n Bun",
"TOWNSVILLE": "Epic Hotdog",
"TOWNSVILLE": "Big George's",
"UNION RD, ASCOT VALE": "Ben's Burgers",
"UNION RD, ASCOT VALE": "World of Wings",
"UNION RD, ASCOT VALE": "Wing World",
"UNION RD, ASCOT VALE": "Big George's Burgers",
"WANTIRNA SOUTH": "World of Wings",
"WANTIRNA SOUTH": "Absurd Bird",
"WANTIRNA SOUTH": "Epic Chicken",
"WANTIRNA SOUTH": "Wing World",
"WARRINGA CRESCENT, HOPPERS CROSSING": "Wing World",
"WARRINGA CRESCENT, HOPPERS CROSSING": "World of Wings",
"WENTWORTHVILLE": "Wing World",
"WENTWORTHVILLE": "World of Wings",
"WEST PYMBLE": "Big George's Burgers",
"WEST PYMBLE": "On The Wing",
"WEST PYMBLE": "Wing World",
"WEST PYMBLE": "World of Wings",
"WEST PYMBLE": "Epic Chicken",
"WEST PYMBLE": "Absurd Bird",
"WEST PYMBLE": "Ben's Burgers",
"WEST PYMBLE": "OTT Burgers",
"WEST PYMBLE": "Legit Burgers",
"WETHERILL PARK": "Absurd Bird",
"WETHERILL PARK": "Epic Chicken",
"WETHERILL PARK": "Wing World",
"WETHERILL PARK": "World of Wings",
"WHITEHORSE ROAD, BALWYN": "On The Wing",
"TOOWOOMBA": "Epic Chicken (Toowoomba)",
"TOOWOOMBA": "Legit Burgers (Toowoomba)",
"TOOWOOMBA": "On The Wing (Toowoomba)",
"TOOWOOMBA": "World of Wings (Toowoomba)",
"TOOWOOMBA": "Wing World (Toowoomba)",
"TOOWOOMBA": "Dog n Bun (Toowoomba)",
"TOOWOOMBA": "Epic Hotdog (Toowoomba)",
"TOOWOOMBA": "Ben's Burgers (Toowoomba)",
"TOOWOOMBA": "Big George's Burgers (Toowoomba)",
"TOWNSVILLE": "Absurd Bird (Townsville)",
"TOWNSVILLE": "Epic Chicken (Townsville)",
"TOWNSVILLE": "Legit Burgers (Townsville)",
"TOWNSVILLE": "OTT Burgers (Townsville)",
"TOWNSVILLE": "World of Wings (Townsville)",
"TOWNSVILLE": "Wing World (Townsville)",
"TOWNSVILLE": "Dog n Bun (Townsville)",
"TOWNSVILLE": "Epic Hotdog (Townsville)",
"TOWNSVILLE": "Ben's Burgers (Townsville)",
"TOWNSVILLE": "Big George's (Townsville)",
"ULTIMO": "Absurd Bird (Ultimo)",
"ULTIMO": "Epic Chicken (Ultimo)",
"ULTIMO": "Legit Burgers (Ultimo)",
"ULTIMO": "OTT Burgers (Ultimo)",
"ULTIMO": "World of Wings (Ultimo)",
"ULTIMO": "Wing World (Ultimo)",
"ULTIMO": "Ungki's (Ultimo)",
"ULTIMO": "Dragon Ear (Ultimo)",
"ULTIMO": "Big George's Burgers (Ultimo)",
"ULTIMO": "Ben's Burgers (Ultimo)",
"ULTIMO": "On The Wing (Ultimo)",
"UNION RD, ASCOT VALE": "World of Wings (Union Road, Ascot Vale)",
"UNION RD, ASCOT VALE": "Wing World (Union Road, Ascot Vale)",
"UNION RD, ASCOT VALE": "Big George's Burgers (Union Road, Ascot Vale)",
"UNION RD, ASCOT VALE": "Ben's Burgers (Union Road, Ascot Vale)",
"WANTIRNA SOUTH": "Absurd Bird (Wantirna South)",
"WANTIRNA SOUTH": "Epic Chicken (Wantirna South)",
"WANTIRNA SOUTH": "World of Wings (Wantirna South)",
"WANTIRNA SOUTH": "Wing World (Wantirna South)",
"WARRINGA CRESCENT, HOPPERS CROSSING": "World of Wings (Warringa Crossing, Hoppers Crossing)",
"WARRINGA CRESCENT, HOPPERS CROSSING": "Wing World (Warringa Crescent, Hoppers Crossing)",
"WENTWORTHVILLE": "World of Wings (Wentworthville)",
"WENTWORTHVILLE": "Wing World (Wentworthville)",
"WEST PYMBLE": "Absurd Bird (West Pymble)",
"WEST PYMBLE": "Epic Chicken (West Pymble)",
"WEST PYMBLE": "World of Wings (West Pymble)",
"WEST PYMBLE": "Wing Wolrld (West Pymble)",
"WEST PYMBLE": "Legit Burgers (West Pymble)",
"WEST PYMBLE": "OTT Burgers (West Pymble)",
"WEST PYMBLE": "Big George's Burgers (West Pymble)",
"WEST PYMBLE": "Ben's Burgers (West Pymble)",
"WEST PYMBLE": "On The Wing (West Pymble)",
"WETHERILL PARK": "World of Wings (Wetherill Park)",
"WETHERILL PARK": "Wing World (Wetherill Park)",
"WETHERILL PARK": "Absurd Bird (Wetherill Park)",
"WETHERILL PARK": "Epic Chicken (Wetherill Park)",
"WHITEHORSE ROAD, BALWYN": "On The Wing (Wetherill Park)",}

query = pcli.locations.list_all(q={"account" :"62fc44dc934376949a733248" })


for i in locations:
    get_location = pcli.locations.list_all(q={"account" :"62fc44dc934376949a733248", "name": i })
    if not get_location:
        url = "https://api.deliverect.com/locations"
        payload = json.dumps({
        "posSettings": {
            "dma": {
            "locationId": "",
            "ordersWebhookURL": "",
            "syncTablesURL": "",
            "syncFloorsURL": "",
            "customHeaders": "",
            "setDefaultPriceLevelOnSync": False,
            "syncProductsURL": "",
            "anonymizeCustomer": False,
            "sendStreetNumber": False,
            "syncBillsURL": "",
            "hasDirectTableIntegration": False,
            "sendDiscount": False,
            "sendDeliveryFee": False,
            "sendServiceCharge": False,
            "sendDeliveryFeeCondition": 0,
            "posOrdersAreAlwaysPaid": False,
            "sendTip": False,
            "sendRebate": False,
            "receiptPaymentURL": "",
            "sortModifiers": 0,
            "bufferOrders": False,
            "deliveryByChannelIsPickup": False,
            "ignoreUnknownOrderStatuses": False,
            "recalcPriceOverrides": False,
            "enableCourierUpdates": False,
            "dontSendCancel": False,
            "orderNoteTemplate": "",
            "readonly": False,
            "logOps": False
            }
        },
        "status": "TESTING",
        "subscriptions": [
            {
            "brandId": "62fc44dc934376949a733247",
            "subscriptionId": "1"
            }
        ],
        "comment": "",
        "enableOutOfStock": False,
        "splitOrderItems": False,
        "enableWorkstations": False,
        "ignorePOSOrderStatuses": False,
        "posSystemId": 20000,
        "address": {
            "remarks": "",
            "phoneNumber": "",
            "houseNumber": "",
            "street": "",
            "postalCode": "",
            "city": "",
            "restaurantName": ""
        },
        "contact": {
            "phoneNumber": "",
            "email": "",
            "firstName": "",
            "lastName": ""
        },
        "timezone": "Australia/Sydney",
        "name": f"{i} +TABLEVIBE",
        "taxExcl": False,
        "enablePickupScreen": False,
        "enablePickupScreenQR": False,
        "pickupScreenSubscriptionId": "",
        "account": "62fc44dc934376949a733248"
        })
        headers = {
        'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJUWkVNakV5TVVZeVJqazJPRGs1TkRjMVF6QXpNMFE1UTBFek1UazNPRFZGTkVJeFF6YzFRZyJ9.eyJpc3MiOiJodHRwczovL2RlbGl2ZXJlY3QuZXUuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTAzMzI5OTY3MjkyNTM2NDEwNjY0IiwiYXVkIjpbImh0dHBzOi8vYXBpLmRlbGl2ZXJlY3QuY29tIiwiaHR0cHM6Ly9kZWxpdmVyZWN0LmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NjQyNjU4MTUsImV4cCI6MTY2NDM1MjIxNSwiYXpwIjoiZ214blpIVFV2R1RPOTdTZ0ttclJFN09iX2NCcmNhaTQiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG9mZmxpbmVfYWNjZXNzIn0.slg0T0WtGfNgvUsZA3irHx5EqbwhJ7HgFTXFwBRh2I3EQljGVbwzKQtqQH9J0KmgixqqdqlxwFIrPrJVPG3OlTV2WZZ-XT4OvuA-h7ZebSXhZL-BxGTjw-cdu-14ZQrfWzq4F38aIPDkqCMpbWQ8-k3TIR2OkFG7vpzxZ273w-bY_LWFGFQUbDdPsLcBfVY37svnRIO6GorSSsq07wnzapRp-ydJVy7Il6bIwPKe0t634xg0VAD0yW6l2JTZ-DEIv7ZOdpUdTvj5i5eCdLgSUYtEzV91BOsUptyeNsJiFov0Xr5ZhSvTzIiBt4ZgxlIpBBHiqNH6bC3DzAtBfQ7o6A',
        'Content-Type': 'application/json'
        }
        response = requests.request("POST", url, headers=headers, data=payload)

        print(response.text)
    else:
        print(i," does already exist")

for key in clMapping:
    get_location = pcli.locations.list_all(q={"account" :"62fc44dc934376949a733248", "name": i })
    print(get_location)
    
    loc_id = get_location.get["_id"]
    
    print(loc_id)

    break


brands = ["Epic Hotdog",
"Ben's Burgers",
"Absurd Bird",
"Epic Chicken",
"Big George's Burgers",
"World of Wings",
"Wing World",
"Dog n Bun",]

location_list = pcli.locations.list_all(q={"account" : "62fc44dc934376949a733248"})
for location in location_list:
    loc_id = location._id
    if location._id != "62fc45091f35f30489effd65":
        for brand in brands:
            url = "https://api.deliverect.com/channelLinks"
            payload = json.dumps({
            "location": f"{loc_id}",
            "account": "62fc44dc934376949a733248",
            "posSystemId": 20000,
            "taxExcl": False,
            "timezone": "Australia/Sydney",
            "fulfillmentEnabled": False,
            "channelSettings": {
                "continuousBillUpdateURL": "",
                "billUpdateURL": "",
                "billPaymentFeedbackURL": "",
                "updatePrepTimeURL": "",
                "autoAcceptOrderStatus": 1,
                "sendTableInfoToNotes": True,
                "statusUpdateURL": "",
                "logChannelOperations": False,
                "sendRejectStatus": False,
                "busyModeURL": "",
                "alwaysSendCalories": False,
                "alwaysSendAllSnoozedProducts": True,
                "snoozeUnsnoozeURL": "",
                "menuUpdateURL": "",
                "coreFlatten": False,
                "minimizeImagesURL": False,
                "resizerFormat": "default",
                "application": "PRODUCTION",
                "channelLocationId": ""
            },
            "posSettings": {
                "dma": {
                "locationId": "",
                "ordersWebhookURL": "",
                "syncTablesURL": "",
                "syncFloorsURL": "",
                "customHeaders": "",
                "setDefaultPriceLevelOnSync": False,
                "syncProductsURL": "",
                "anonymizeCustomer": False,
                "sendStreetNumber": False,
                "syncBillsURL": "",
                "hasDirectTableIntegration": False,
                "sendDiscount": False,
                "sendDeliveryFee": False,
                "sendServiceCharge": False,
                "sendDeliveryFeeCondition": 0,
                "posOrdersAreAlwaysPaid": False,
                "sendTip": False,
                "sendRebate": False,
                "receiptPaymentURL": "",
                "sortModifiers": 0,
                "bufferOrders": False,
                "deliveryByChannelIsPickup": False,
                "ignoreUnknownOrderStatuses": False,
                "recalcPriceOverrides": False,
                "enableCourierUpdates": False,
                "dontSendCancel": False,
                "orderNoteTemplate": "",
                "readonly": False,
                "logOps": False,
                "orderItemRemarks": "intactItemRemarks",
                "alwaysSendAllSnoozedProducts": True,
                "snoozeWhenOutOfStock": None,
                "averagePreparationTime": 15,
                "averageDeliveryTime": 15
                }
            },
            "paymentProfile": "",
            "brandId": "62fc44dc934376949a733247",
            "menuUrl": "",
            "status": 2,
            "name": f"{brand} - TableVibe",
            "channel": 10154,
            "anonymizeCustomer": False,
            "bufferOrders": False,
            "defaultPreparationTime": 15,
            "averageDeliveryTime": 15,
            "mockPOS": False,
            "logPOS": False,
            "application": "PRODUCTION"
            })
            headers = {
            'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJUWkVNakV5TVVZeVJqazJPRGs1TkRjMVF6QXpNMFE1UTBFek1UazNPRFZGTkVJeFF6YzFRZyJ9.eyJpc3MiOiJodHRwczovL2RlbGl2ZXJlY3QuZXUuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTAzMzI5OTY3MjkyNTM2NDEwNjY0IiwiYXVkIjpbImh0dHBzOi8vYXBpLmRlbGl2ZXJlY3QuY29tIiwiaHR0cHM6Ly9kZWxpdmVyZWN0LmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NjQyNjU4MTUsImV4cCI6MTY2NDM1MjIxNSwiYXpwIjoiZ214blpIVFV2R1RPOTdTZ0ttclJFN09iX2NCcmNhaTQiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG9mZmxpbmVfYWNjZXNzIn0.slg0T0WtGfNgvUsZA3irHx5EqbwhJ7HgFTXFwBRh2I3EQljGVbwzKQtqQH9J0KmgixqqdqlxwFIrPrJVPG3OlTV2WZZ-XT4OvuA-h7ZebSXhZL-BxGTjw-cdu-14ZQrfWzq4F38aIPDkqCMpbWQ8-k3TIR2OkFG7vpzxZ273w-bY_LWFGFQUbDdPsLcBfVY37svnRIO6GorSSsq07wnzapRp-ydJVy7Il6bIwPKe0t634xg0VAD0yW6l2JTZ-DEIv7ZOdpUdTvj5i5eCdLgSUYtEzV91BOsUptyeNsJiFov0Xr5ZhSvTzIiBt4ZgxlIpBBHiqNH6bC3DzAtBfQ7o6A',
            'Content-Type': 'application/json'
            }
            print(payload)
            response = requests.request("POST", url, headers=headers, data=payload)

            print(response.text)
            print("created mashalllaaaaah")