#Channels: 
# 9 = JE 
# 2 = Deliveroo
# 7 = Uber
# 10015 = Order ahead

whole_acc_query = {'account' : '5e81f14758168e0001d981d5','channel' : 7 }
some_loc_query = {'account' : '5e81f14758168e0001d981d5',"location" :{"$in" : ["60c7715aef3e6f4a7774b933","60c7716bef3e6f4a7774ca99","60c862343fa4f3de8c9ef75b",] }}
one_loc_query = {'account' : "5e81f14758168e0001d981d5" , 'location' : '612fbb81a367074635c669fa'}
env = pcli
links = env.channelLinks.list_all(q=one_loc_query)
for link in links:
    channel =   link.get('channel')
    if channel == 9:
        env.channelLinks.update(link,{
        "productLocation": "5f0830509f26c0077d566597",
        
        "posSettings": {
            "simphony": {
                "posOrdersAreAlwaysPaid": False,
                "sendCheckId": True,
                "sendOrderType": False,
                "rushOrder": False,
                "vipOrder": False,
                "checkEmplOrder": False,
                "allowPartialOrder": False,
                "futureOrder": False,
                "hasAuth": True,
                "revenueCenter": "11",
                "employeeObjectNumber": "8954",
                "posVersion": "18.2",
                "paidPaymentType": "309",
                "discountId": "826002002",
                "notPaidPaymentType": "902",
                "tax1": 5,
                "taxObjectNumber1": 3,
                "orderTypeId": "4",
                "username": "svc_deliverect_prod",
                "password": "w2g@V$T2*ejR",
                "itemSubLevel": 3,
                "itemMenuLevel": 1,
                "timeZone": "Europe/London",
                "bufferOrders": False,
                "anonymizeCustomer": False,
                "readonly": False,
                "useCommaAsDecimalCharacter": False,
                "cropCustomerName": False,
                "noteTemplate": "",
                "sendAddressInNoteItem": False,
                "noteItemPlu": "",
                "checkToFireDateAsap": False,
                "orderNoteTemplate": "",
                "discountPLU": "",
                "serviceChargePLU": "",
                "deliveryPLU": "",
                "modifierMultiplier": "",
                "taxExcl": False,
                "productsSyncRanges": "",
                "productsFamilyGroups": "",
                "dontLinkModGroups": False,
                "tax2": 20,
                "taxObjectNumber2": 2,
                "autoFinalizeOrders": True,
                "averagePreparationTime": 1,
                "usePLUForCharges": False,
                "pCheckInfoLinesTemplate": "",
                "dontSendPhoneNumber": False,
                "onlySendOrderDisplayIdForCheckId": False,
                "putNoteItemsAtTop": False,
                "paginateProductSync": False,
                "replaceNonAsciiSymbols": False
                }},
                "channelSettings":{
                    "sendDiscount": True,
                    "sendDeliveryFee": False,
                    "sendServiceCharge": False,
                    "application": "PRODUCTION",
                    
                }})
    elif channel == 7:
        env.channelLinks.update(link,{
        "productLocation": "5f0830509f26c0077d566597",
        
        "posSettings": {
            "simphony": {
                "posOrdersAreAlwaysPaid": False,
                "sendCheckId": True,
                "sendOrderType": False,
                "rushOrder": False,
                "vipOrder": False,
                "checkEmplOrder": False,
                "allowPartialOrder": False,
                "futureOrder": False,
                "hasAuth": True,
                "revenueCenter": "11",
                "employeeObjectNumber": "8955",
                "itemSubLevel": 3,
                "itemMenuLevel": 1,
                "posVersion": "18.2",
                "orderTypeId": "5",
                "discountId": "826002002",
                "paidPaymentType": "310",
                "notPaidPaymentType": "902",
                "tax1": 5,
                "taxObjectNumber1": 4,
                "password": "w2g@V$T2*ejR",
                "username": "svc_deliverect_prod",
                "timeZone": "Europe/London",
                "bufferOrders": False,
                "logOps": True,
                "priceLevel": 2,
                "snoozeWhenOutOfStock": None,
                "cropCustomerName": False,
                "noteItemPlu": "",
                "serviceChargeId": None,
                "anonymizeCustomer": False,
                "readonly": False,
                "useCommaAsDecimalCharacter": False,
                "noteTemplate": "",
                "sendAddressInNoteItem": False,
                "checkToFireDateAsap": False,
                "orderNoteTemplate": "",
                "discountPLU": "",
                "serviceChargePLU": "",
                "deliveryPLU": "",
                "modifierMultiplier": "",
                "taxExcl": False,
                "productsSyncRanges": "",
                "productsFamilyGroups": "",
                "dontLinkModGroups": False,
                "tax2": 20,
                "taxObjectNumber2": 2,
                "autoFinalizeOrders": True,
                "averagePreparationTime": 1,
                "usePLUForCharges": False,
                "pCheckInfoLinesTemplate": "",
                "dontSendPhoneNumber": False,
                "onlySendOrderDisplayIdForCheckId": False,
                "putNoteItemsAtTop": False,
                "paginateProductSync": False,
                "replaceNonAsciiSymbols": False
    }},
        "channelSettings": {
            "useNewAPI": True,
            "checkRemoteSnoozes": False,
            "validateMenu": False,
            "sendDiscount": True,
            "sendDeliveryFee": False,
            "sendServiceCharge": False,
            "application": "SIMPHONY",
            
                }})
    elif channel == 1:
        env.channelLinks.update(link,{
        "productLocation": "5f0830509f26c0077d566597",
        
        "posSettings": {
            "simphony": {
                "posOrdersAreAlwaysPaid": False,
                "sendCheckId": True,
                "sendOrderType": False,
                "rushOrder": False,
                "vipOrder": False,
                "checkEmplOrder": False,
                "allowPartialOrder": False,
                "futureOrder": False,
                "hasAuth": True,
                "revenueCenter": "11",
                "employeeObjectNumber": "8955",
                "itemSubLevel": 3,
                "itemMenuLevel": 1,
                "posVersion": "18.2",
                "orderTypeId": "5",
                "discountId": "826002002",
                "paidPaymentType": "310",
                "notPaidPaymentType": "902",
                "tax1": 5,
                "taxObjectNumber1": 4,
                "password": "w2g@V$T2*ejR",
                "username": "svc_deliverect_prod",
                "timeZone": "Europe/London",
                "bufferOrders": False,
                "logOps": True,
                "priceLevel": 2,
                "snoozeWhenOutOfStock": None,
                "cropCustomerName": False,
                "noteItemPlu": "",
                "serviceChargeId": None,
                "anonymizeCustomer": False,
                "readonly": False,
                "useCommaAsDecimalCharacter": False,
                "noteTemplate": "",
                "sendAddressInNoteItem": False,
                "checkToFireDateAsap": False,
                "orderNoteTemplate": "",
                "discountPLU": "",
                "serviceChargePLU": "",
                "deliveryPLU": "",
                "modifierMultiplier": "",
                "taxExcl": False,
                "productsSyncRanges": "",
                "productsFamilyGroups": "",
                "dontLinkModGroups": False,
                "tax2": 20,
                "taxObjectNumber2": 2,
                "autoFinalizeOrders": True,
                "averagePreparationTime": 1,
                "usePLUForCharges": False,
                "pCheckInfoLinesTemplate": "",
                "dontSendPhoneNumber": False,
                "onlySendOrderDisplayIdForCheckId": False,
                "putNoteItemsAtTop": False,
                "paginateProductSync": False,
                "replaceNonAsciiSymbols": False
    }},
        "channelSettings": {
            "useNewAPI": True,
            "checkRemoteSnoozes": False,
            "validateMenu": False,
            "sendDiscount": True,
            "sendDeliveryFee": False,
            "sendServiceCharge": False,
            "application": "SIMPHONY",
            
                }})
    elif channel == 2:
        env.channelLinks.update(link,{
        "productLocation": "5f0830509f26c0077d566597",
        
        "posSettings": {
            "simphony": {
                "posOrdersAreAlwaysPaid": False,
            "revenueCenter": "11",
            "employeeObjectNumber": "8932",
            "paidPaymentType": "308",
            "notPaidPaymentType": "902",
            "discountId": "826002002",
            "orderTypeId": "3",
            "itemMenuLevel": 1,
            "itemSubLevel": 3,
            "posVersion": "18.2",
            "sendCheckId": True,
            "sendOrderType": False,
            "timeZone": "Europe/London",
            "rushOrder": False,
            "vipOrder": False,
            "checkEmplOrder": False,
            "allowPartialOrder": False,
            "futureOrder": False,
            "hasAuth": True,
            "tax1": 5,
            "taxObjectNumber1": 4,
            "password": "w2g@V$T2*ejR",
            "username": "svc_deliverect_prod",
            "bufferOrders": True,
            "readonly": False,
            "logOps": True,
            "anonymizeCustomer": False,
            "useCommaAsDecimalCharacter": False,
            "cropCustomerName": False,
            "noteTemplate": "",
            "sendAddressInNoteItem": False,
            "noteItemPlu": "",
            "checkToFireDateAsap": False,
            "orderNoteTemplate": "",
            "discountPLU": "",
            "serviceChargePLU": "",
            "deliveryPLU": "",
            "modifierMultiplier": "",
            "taxExcl": False,
            "productsSyncRanges": "",
            "productsFamilyGroups": "",
            "dontLinkModGroups": False,
            "priceLevel": 2,
            "pCheckInfoLinesTemplate": "",
            "dontSendPhoneNumber": False,
            "onlySendOrderDisplayIdForCheckId": False,
            "tax2": 20,
            "taxObjectNumber2": 2,
            "autoFinalizeOrders": True,
            "averagePreparationTime": 1,
            "tax3": "",
            "tax4": "",
            "taxObjectNumber3": "",
            "taxObjectNumber4": "",
            "usePLUForCharges": False,
            "putNoteItemsAtTop": False,
            "tipPLU": "",
            "paginateProductSync": False,
            "replaceNonAsciiSymbols": False,
            "addTagsToNote": False
            }},
        "channelSettings": {
            "brandId": "pretamanger-gb",
            "countryCode": "GB",
            "sendDiscount": True,
            "sendDeliveryFee": False,
            "sendServiceCharge": False,
            "application": "PRODUCTION",
            
            "readonly": False,
            "storeId": "",
            "sendRejectStatus": False,
            "sendDeliveryFeeCondition": 0,
            "updatePrepStage": False,
            "sendTip": False,
            "checkRemoteSnoozes": False
            }})
            
    elif channel == 10005:
        env.channelLinks.update(link,{
        "productLocation": "5f0830509f26c0077d566597",
        
        "posSettings": {
            "simphony": {
                "posOrdersAreAlwaysPaid": False,
                "sendCheckId": True,
                "sendOrderType": False,
                "rushOrder": False,
                "vipOrder": False,
                "checkEmplOrder": False,
                "allowPartialOrder": False,
                "futureOrder": False,
                "hasAuth": True,
                "revenueCenter": "11",
                "employeeObjectNumber": "8963",
                "posVersion": "18.2",
                "itemMenuLevel": 1,
                "itemSubLevel": 3,
                "orderTypeId": "6",
                "paidPaymentType": "311",
                "discountId": "826002001",
                "notPaidPaymentType": "901",
                "serviceChargeId": "251",
                "tax1": 5,
                "taxObjectNumber1": 4,
                "timeZone": "Europe/London",
                "bufferOrders": True,
                "logOps": True,
                "anonymizeCustomer": False,
                "readonly": False,
                "useCommaAsDecimalCharacter": False,
                "cropCustomerName": True,
                "noteTemplate": "",
                "sendAddressInNoteItem": False,
                "noteItemPlu": "",
                "checkToFireDateAsap": False,
                "orderNoteTemplate": "",
                "discountPLU": "",
                "serviceChargePLU": "",
                "deliveryPLU": "",
                "modifierMultiplier": "",
                "taxExcl": False,
                "username": "svc_deliverect_prod",
                "password": "w2g@V$T2*ejR",
                "priceLevel": 2,
                "pCheckInfoLinesTemplate": "Order #{displayOrderId}{br}Ready for: {pickUpTime}{br}Customer: {customerName}{br}Notes: {orderNote}",
                "dontSendPhoneNumber": True,
                "snoozeWhenOutOfStock": None,
                "onlySendOrderDisplayIdForCheckId": True,
                "averageDeliveryTime": 0,
                "averagePreparationTime": 5,
                "productsSyncRanges": "",
                "productsFamilyGroups": "",
                "dontLinkModGroups": False,
                "tax2": 20,
                "taxObjectNumber2": 2,
                "autoFinalizeOrders": True,
                "usePLUForCharges": False,
                "putNoteItemsAtTop": False,
                "paginateProductSync": False,
                "replaceNonAsciiSymbols": False
                }},
        "channelSettings": {    
                "allowUpdateMenuPrepTime": False,
                "alwaysSendAllSnoozedProducts": False,
                "menuUpdateURL": "https://api1.pret.com/v1/deliverect/updatemenu",
                "statusUpdateURL": "https://api1.pret.com/v1/deliverect/orderstatus",
                "busyModeURL": "https://api1.pret.com/v1/deliverect/busymode",
                "activateURL": "https://api1.pret.com/v1/deliverect/channelstatus",
                "disabledProductsURL": "https://api1.pret.com/v1/deliverect/productdisable",
                "snoozeUnsnoozeURL": "https://api1.pret.com/v1/deliverect/snoozestatus",
                "sendDiscount": True,
                "sendDeliveryFee": False,
                "sendServiceCharge": False,
                
                "updateMenuPrepTimeURL": "",
                "application": "PRODUCTION",
                "alwaysSendCalories": False,
                "sendRejectStatus": False,
                "sendDeliveryFeeCondition": 0,
                "sendTableInfoToNotes": False,
            }})